### ISSUE TITLE
implement buildPluginInfo by parsing JSON

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/dplug#105]
The information is currently duplicated in `plugin.json` and the `buildPluginInfo` virtual method. 

`plugin.json` is needed in part because of macOS packaging of plugins. The decision was to remove `buildPluginInfo` as a mandatory override.

It is a challenging bug because plugins are `@nogc` but JSON parsers usually throw exceptions. It would be interesting to parse this information at compile-time!

```
abstract PluginInfo buildPluginInfo();
```

would be replaced in dplug/client/dplug/client.d by:
```
enum PluginInfo pluginInfo = parsePlugingInfo!("plugin.json"); // compile-time parser
```
or
```
enum PluginInfo pluginInfo = parsePlugingInfo("plugin.json"); // runtime parser but CTFE'd
```

**Explanations about the various JSON files:**
- `dub` consumes `dub.json`
- `release` consumes `plugin.json`, and calls `dub`
- `release` is only required on macOS, on Windows regular `dub` is sufficient

**Comment by p0nce** [comment]
Add three keys to `plugin.json`
- does receive MIDI messages
- does output MIDI messages
- has an UI

**Comment by p0nce** [comment]
Must delay this, resources within a path don't pass with `import(subdir/filename)` which prevent to `-J.`

**Comment by abaga129** [comment]
`string json = import("plugin.json") ` seems to work, but parsing the string is difficult.  Even manually parsing seems to be a problem since building strings using the `~` operator needs the GC.

**Comment by p0nce** [comment]
Hi, what if you force a CTFE context with enum?
My hope is that perhaps in CTFE we are allowed to use GC and exception?

```
string json = import("plugin.json");
enum JSONValue info = parseJSON(text);
```
It's a bit unfortunate for the sub-directory, I remember `plugin.json` needed to be in a sub-directory which makes things worse.

**Comment by p0nce** [comment]
OK I tried and indeed std.json was not designed to operate in CTFE. You can parse but not extract keys.
`"."` in `"stringImportPaths"` seemingly worked.

We have many other options, by order of preference from my side:
- use ctini and change the format https://github.com/krendil/ctini
- find a JSON parser that works at compile-time
- finds the name of the client class in D file `release` tool, then compile a D program that instantiate it and calls `buildPluginInfo`
- loosely parser the right D file in `release` tool
- insert a special comment on top of `buildPluginInfo` with the JSON information (again a duplication)

**Comment by abaga129** [comment]
One more possibility could be to use `ctRegex` in `std.regex` to parse the JSON string.  Form the documentation on dlang.org  "uses string mixins and CTFE to generate a highly optimized regular expression automaton that is generated during compilation."  I may experiment with this idea.

**Comment by p0nce** [comment]
Remaining work:
- [ ] `buildPluginInfo` override will disappear
- [ ] additional fields in plugin.json (hasGUI)
- [ ] formatting

**Comment by p0nce** [comment]
Note: `plugin.json`is now mandatory, even if not using `release`.

**Comment by p0nce** [comment]
What remains: we still have the buildPluginInfo override. In a way that's nice because it makes it clear that parsing `plugin.json` is not 100% required, but still it's more complicated than if `dplug:client` was handling this. However there is no dub way to do that.

**Comment by p0nce** [comment]
It is possible to import(filename) without the right string import path if filename is a compile-time value. But that would make `dplug.client.client.Client` a template.

**Comment by abaga129** [comment]
What if `dplug.client.client.Client` does `static `static PluginInfo pluginInfo = parsePluginInfo(import("plugin.json")` and then `buildPluginInfo` returns `pluginInfo` the same way that the inherited class does now.  Then `buildPluginInfo` would be abstract and `plugin.json` would be required.

I think this should be possible, but I'm not sure if it would be a better solution since `plugin.json` would be required.

**Comment by p0nce** [comment]
That was the plan (it's ok if plugin.json is required, saves 4 lines in each plugin) but the problem is when compiling `dplug:client`: the compiler chokes on `import("plugin.json")`.

- One way around this is to buid `dplug:client` subpackages with `"."` as but it's ugly and makes DUB hang

- The other way is to templatize `dplug.client.client.Client` and pass the JSON data (or file path) in a string template parameter. The downside is now that template don't have extensive semantic analysis but this is more futuree-proof.

Maybe there are other ways, haven't found yet.

**Comment by abaga129** [comment]
I like the second option, however i'm not sure if my current knowledge of D is up the task.

Also I had an idea and wondered what your thoughts were.  The contains of `plugin.json` can be placed inside `dub.json` and parsing `dub.json` works perfectly fine.  Then `plugin.json` is no longer needed, however it may make it less clear how the JSON parsing actually works.

**Comment by p0nce** [comment]
It's an interesting question and I'm not even sure I remembers all the details.
Originally `plugin.json` was indeed an extension of `dub.json`.

At one point DUB started supporting `dub.sdl` as an alternative to `dub.json`. 
But parsing SDL is much more involved than parsing JSON so Dplug would not support plugin projects using dub.sdl`.

IIRC the idea behind separation was that :
- separation of concerns,
- one day Dplug would support `dub.sdl` through the `dub describe` command

As of now, `release` still requires both `dub.json` (for plugin name and configurations) and `plugin.json` because `dub describe` can be incredibly slow on slow networks.
(in general, a DUB command will poll the network unless you've specified `--skip-registry=all` but that prevents dependencies update).

So for now `dub.sdl` is still not supported.

**Comment by p0nce** [comment]
Closed as parsing plugin.json at compile-time is now supported.
