### ISSUE TITLE
Fix DDoc warnings (was: More Documentation)

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#158]
First user report back "aha" moments

- [x] "Learning how to draw an image." (EDIT: will be made clear by `dplug:flat-widgets`)
   * The first difficulty was understanding what DirtyRects[] in onDraw actually was.
   * Realizing that OwnedImage!RGBA could be cropped with a dirty rect.
   * Learning to blend the RGBA from the image with the input diffuse map.

- [x] Understanding how to use mallocEmplace and AlignedBuffer
   * "For me @nogc is very new and so it took me a long time to learn how to work this way. I'm still learning.  I think a simple guide to working with @nogc would be very benefitial to newcomers."

- [x] Let's fix Ddoc

**Comment by p0nce** [comment]
- Distort should showcase PBR example with backgrounds

**Comment by abaga129** [comment]
I could create an example showcasing a background drawn from an image if you think that may be useful. Or alternatively I can create a wiki page

**Comment by p0nce** [comment]
mmm, I was intending distort to showcase PBR. What would be great is copy the FAQ into the wiki, then link from readme.

**Comment by p0nce** [comment]
Another very useful thing that would help, and that only you can do, is to speak a little about Dplug, the tradeoffs, the shortcomings, in your blog.

**Comment by abaga129** [comment]
Yeah I would be glad to write a post about dplug.  I have considered it before but just hadn't gotten around to doing it yet.  My blog doesn't get much traffic but I suppose every little bit helps.

**Comment by abaga129** [comment]
I've considered writing up a forum post about it on the kvr dsp forum also just to get a little more exposure for it.

**Comment by p0nce** [comment]
I think it's better not to communicate too much on KVR until you've released your plugin. The people at KVR DSP forum have a long-time investment in C++ and are keen on pointing out perceived problem. So my tone here is usually a bit on the background "hey, this thing exists".

**Comment by p0nce** [comment]
Now every file has a description text in DDoc (except the many files in x11/).
