### ISSUE TITLE
Some Elements not receiving all mouse information

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/dplug#173]
I have a `UIElement` that gets `onMouseEnter()` called but not `onMouseClick()`.  I set breakpoints to be sure.  I have 4 of these being drawn on the gui and 2 of them recieve mouse click events and the other 2 do not.

Here is the code that I'm using.
```D
    override bool onMouseClick(int x, int y, int button, bool isDoubleClick, MouseState mstate)
    {
        // double-click => set to default
        //_param.beginParamEdit();
        //_param.setFromGUI(!_param.value());
        //_param.endParamEdit();
        return true;
    }

    override void onMouseEnter()
    {
        setDirtyWhole();
    }
```

**Comment by p0nce** [comment]
All UIElement have a `zOrder` property that is used for ordering widgets for `onDraw`.

This `zOrder` is also used for dispatching mouse click.
The idea is that `position()` is used, but in the case of overlapping `positions` the item with the highest zOrder should win.
https://github.com/AuburnSounds/dplug/blob/master/gui/dplug/gui/element.d#L220

Though I'm not sure why the sort is unstable: https://github.com/AuburnSounds/dplug/blob/master/gui/dplug/gui/element.d#L220 this may be the bug.

Also I'm not sure if this ordering works well for 2-level or more of hierarchy. If two "cousins" have overlapping _position then there is a chance the click would not go to the highest `zOrder` .

Maybe try assigning a higher zOrder (eg: 1) to the element that should receive the click.

A third possibility is that zOrder is not seen for `mouseEnter.

**Comment by abaga129** [comment]
Im unable to test it right now, but I think changing the zOrder might be the way to fix it. I was unaware that `UIElement` has a `setZOrder()` method I will try that as soon as I am able. 

In answer to your questions
- No I havent changed zOrder manually yet
- Yes it does have overlapping positions with two other elements. They are both added as children before the one that isnt receiving clicks.

It is still strange to me that I have 4 identical Elements that dont overlap positions with each other, but the do each overlap with 2 other Elements that I mentioned before. Two of the elements receive click information and 2 dont.

**Comment by p0nce** [comment]
OK so they are all children with the same parent and same zOrder, so what happens is that the non-stable sort don't preserve the order of addChild (when having the same zOrder, this order is supposed to prevail). I'll try to add a stable sort instead, there is one for the drawing list.

**Comment by p0nce** [comment]
TODO try to use https://github.com/AuburnSounds/dplug/blob/9e9d91e807e135d75f5415a8b2c4fe07dc3c887f/core/dplug/core/nogc.d#L433

**Comment by abaga129** [comment]
I can confirm that setting the `zOrder` manually worked.  I set all 4 `UIElements` to have  a `zOrder` of  1 and they are now all receiving mouse clicks properly.  It's still unclear to me why two of them worked with default `zOrder` and two did not.

**Comment by p0nce** [comment]
Items with identical zOrder must display in the tree order, so we use the ordering of the hierarchy: parent displayed before first child displayed before second child etc.. 

It's a bit the same with clicks, except the sort is broken so it shuffle the children with same zOrder (not stable).
