### ISSUE TITLE
x11window not drawing anything

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/dplug#178]
I have tested plugins in two hosts on linux now: Bitwig and Audacity.  Both create windows and process audio correctly but the windows are empty in both hosts.  I will investigate this further.

**Comment by p0nce** [comment]
Also it looks like x11window does not work like other windows wrt how dirty areas work. Animation only Expose or something should call onDraw, currently strange.

**Comment by MartinNowak** [comment]
Yes, let's track it here, sounds like the same problem I had with Renoise, the Window isn't redrawn.
https://github.com/AuburnSounds/dplug/pull/171#issuecomment-317221434
Will have a look once I find time (not that much unfortunately). Maybe I can reuse some of my old X11 code https://github.com/MartinNowak/appf/blob/292ede141c155924c6a1fd80491b328c50b81edb/src/appf/window.d.
It's a bit tricky to debug plugins in a host, so some simpler fake host would be helpful. Any ideas?

**Comment by abaga129** [comment]
I have found a way to debug plug-ins on linux.  I use VS Code with the code-d and debug-d extensions.  You can create a debug configuration to launch audacity with gdb and then load the plugin from audacity.

**Comment by p0nce** [comment]
`stress-plugin` is supposed to create a window and host a plugin inside, however I'm not sure on what OS it works exactly.

**Comment by p0nce** [comment]
https://github.com/dlang/dub/issues/697

**Comment by abaga129** [comment]
It seems that `X11Window` is not receiving the `parentInfo` correctly.  If I set `parentInfo` to null, it will create a separate window and fill it with white pixels.  Otherwise, nothing is drawn at all.

**Comment by p0nce** [comment]
Windows receive null as `parentInfo` when they are supposed to be stand-alone (though the interface is incomplete to really make a host out of it). It's just for testing and stress-plugin.

This is not the case when such window are created for plugins, in this case the parent window handle (API-specific) is given by the host.

**Comment by abaga129** [comment]
Perhaps having the plugin create it's own host window would be okay for now until we can figure out how to properly get the parent window handle in Linux?  I know this is a crude workaround but I think it could work.

**Comment by abaga129** [comment]
Some further digging has yielded this
https://github.com/Ardour/ardour/blob/fd8053da9eaf5e97aaa978d971410d4f246c7138/gtk2_ardour/linux_vst_gui_support.cc#L730

Here is where the dispatcher sends the Display and the Parent Window handle.  I don't quite understand how the dispatcher works but I think this is the right place to start looking into how X11 is implemented for lxvst.

I'm going to see what I can find with Audacity also.

**Comment by p0nce** [comment]
IIRC Ardour has its own flavour that is not VST, so I think we should really look into other hosts first.

**Comment by abaga129** [comment]
Yeah, Audacity is probably the best to target first.   I updated my findings in my previous comment.

I'm thinking once we get a handle to the parent window from the host.  All we need to do is create a thread that will wait and respond to events.  From what I've read, it doesn't matter if we own the connection to X Display or if we use the one given to us by  the host, so it will probably be easiest to just create our own connection like Rikki has.

**Comment by p0nce** [comment]
> it will probably be easiest to just create our own connection like Rikki has.

Also since Ardour says most plugins do that.

See the unittest in dplug.core.thread to create a thread:
https://github.com/AuburnSounds/dplug/blob/master/core/dplug/core/thread.d#L190

**Comment by abaga129** [comment]
Fixed in b05e2c2
