### ISSUE TITLE
Is it possible to compile 64 bit plugins in windows?

### ISSUE THREAD

**Issue by jmriddell** [AuburnSounds/dplug#182]
readme.md says it is possible but can't figure out how

**Comment by p0nce** [comment]
It's a bit complicated, you have to make sure you can build D programs in 64-bit.
For both LDC and DMD this is done with the MS linker, so you need to install a Visual Studio.

For DMD the installer will put the right information in sc.ini, provided you have installed Visual Studio before. I use VS2013 for developping and VS2015 for linking, so in my sc.ini I have the following:
```
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.1\
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
UCRTVersion=10.0.10240.0
```
Once it's correctly configured you can make 64-bit D programs with DMD.

LDC works more automatically I believe, but it always use VS linker be it in 32-bit or 64-bit.
