### ISSUE TITLE
Installer for Mac

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#192]
A number of Mac users click on the plug-in and are confused that it doesn't install.
A DMG like TDR does seems ideal. (EDIT: not sure why DMG is any useful today)

**Comment by p0nce** [comment]
State of the art to day seems to be .pkg instead.
https://www.kvraudio.com/forum/viewtopic.php?f=33&t=506798&p=7104414&hilit=pkgbuild#p7104414

**Comment by p0nce** [comment]
- [ ] Synthesize the `pkgbuild` calls from `dplug-build`
- [ ] Synthesize a distribution.txt `dplug-build`
- [ ] Merge all .pkg from a single `dplug-build` instantiation (if Universal Binary exist, ignore 32-bit and 64-bits)
- [ ] Call `signtool`

**Comment by p0nce** [comment]
`distribution.txt` has many problems:
- [ ] signature not accepted
- [ ] no choice seen
- [ ] installation doesn't happen

**Comment by p0nce** [comment]
licence file from`plugin.json` must now be markdown file ending in `.md`.

**Comment by p0nce** [comment]
- [ ] descriptive text for options
- [ ] remove default line choice?
- [ ] PNG background

**Comment by 0xEAB** [comment]
> licence file must now be markdown or HTML files

why no txt?

**Comment by p0nce** [comment]
`.txt` is not accepted by the Mac installer script!
What is accepted is just `.html` from what I see.

So I thought of converting the .txt file to HTML but that would lost all newlines and paragraph.
`.txt` is easily converted to Markdown which is why it got the preference.

Licence file will also be converted for distribution. This is a breaking change.

**Comment by p0nce** [comment]
Signing intermediate single-format `.pkg` => still not good with Gatekeeper.

- [ ] get an application certificate and sign the bundles

**Comment by p0nce** [comment]
- [ ] proper signing

**Comment by p0nce** [comment]
Analysis of what people do.

u-he: 
- ZIP not signed, 
- pkg fails `spctl -a`, fails `codesign -dvvv`, pass `pkgutil --check-signature`

**Comment by p0nce** [comment]
I really don't understand why so may rely on DMG vs just a PKG.

**Comment by p0nce** [comment]
Available in v8.1

**Comment by 0xEAB** [comment]
So how does this feature work now?
Does `dplug-build` do everything automatically?

**Comment by p0nce** [comment]
I need to write a Wiki article sorry.

**Functionality**

- on MacOS when `dplug-build` receive the new `--installer` switch, it gathers all things built (except intermediate artifacts that are built into `builds/temp`) **in the same cmdline invocation** into a merged package. This package is named `build/<pluginname>-<configuration-suffix>-<version>.pkg`.
- this configuration suffix is taken from the configuration name. If the configuration is named `VST-SILVER-EDITION` then the configuration-suffix is `SILVER-EDITION`
- `dplug-build` will also create a `.pkg` for each non-temp build, those could eventually be distributed but will lack a licence and a background file.
- no change for Windows, `--installer` not yet supported
- 32-bit/64-bit/UniversalBinary should be suported, though I haven't tried since I can't build 32-bit anymore


**Requirements**
- the Mac installer need an optional PNG background, `dplug-build` will help with the new `plugin.json` key:
``` json
--- plugin.json ---
"installerPNGPath": "../installer-background.png",
```
- You'll need to convert `license.txt` into a `license.md`, dplug-build will warn about that
- **You'll need to be a registered Apple developer in the Apple developer program, and install 2 Apple certificate** (one for "3rd party Developer Installer" and the other for "3rd party Developper application"). `dplug-build` will help filling the new `plugin.json` entry:
```json
--- plugin.json ---
 "developerIdentity-osx": "XXXXXXXXXX",
