### ISSUE TITLE
Can't find distort.d

### ISSUE THREAD

**Issue by menglee** [AuburnSounds/Dplug#194]
Hi,
I am following the directions to build the plugin in example/distort. But I don't see a distort.d file.

**Comment by abaga129** [comment]
Ah this is because the distort example was changed in 9cfe47b, but the wiki hasn't been updated with this change.  `distort.d` was split into `main.d` and `gui.d`.  I will update the wiki.

**Comment by p0nce** [comment]
Thanks :)
