### ISSUE TITLE
upgrade stb_truetype.d 

### ISSUE THREAD

**Issue by lyrachord** [AuburnSounds/Dplug#207]
stb_truetype.d port version is v0.7.
stb.truetype.h updated to 1.7, and a new algorithm already introduced.

ONLY one time of sorting employed in the new algorithm.

BTW:
Please NOTE: the new algorithm has a design bug, new turn sorted segments maybe insert into current active edge list. re-sort needed. but the author not consider it.

**Comment by p0nce** [comment]
What is the problem you encounter with the current stb_truetype.d and why exactly should it be upgraded?

**Comment by p0nce** [comment]
If you are using Dplug do not hesitate to jump in the Discord and say hi.

**Comment by p0nce** [comment]
Closed because no answer.
