### ISSUE TITLE
[X11] Remove the function asyncEventHandling from X11 window implementation

### ISSUE THREAD

**Issue by rikkimax** [AuburnSounds/Dplug#220]
The asyncEventHandling method from the X11 window implementation violates a central rule to windowing system libraries which is that they are not thread-safe.

This will cause issues, and upon testing (during implementation of drag and drop) found that it would indeed cause an error similar to a segfault.

https://github.com/AuburnSounds/Dplug/blob/master/window/dplug/window/x11window.d#L230

**Comment by rikkimax** [comment]
The while loop inside of waitEventAndDispatch should become an if statement also, for consistency reasons.

**Comment by p0nce** [comment]
It does looks racey, but what exactly is the data/call being raced on? It seems like the thread created on Windows creation is the only one to call waitEventAndDispatch and redraw so I don't see what problems will happen if there is only one thread doing that.

**Comment by p0nce** [comment]
The problem with the while is that the thread loop does something not ideal:

```
 while(!x11WindowMapping.empty)
        {
            waitEventAndDispatch();
            redraw();
            //Sleep for ~16.6 milliseconds (60 frames per second rendering)
            usleep(16666);
        }
```
So, say there are several mouse movements and the plugin "redraw" one time per mouse movement, it may make things stutter (cc: @abaga129 )

The real problem with X11 windowing is that drawing should be deccorelated from events like in all other window implementation. However since Linux users are a tiny fraction of Windows and OSX users there is less pressure to fix it.

**Comment by rikkimax** [comment]
The while loop is only a problem for consistency reasons.
Windows only executes once, X11 forever. Just got to pick one and I believe Windows is correct as it gives the most control to the user.

Regarding asyncEventHandling, that is indeed a problem on the xlib and friends side. You just can't meddle with it like that without causing problems.

**Comment by p0nce** [comment]
OK so the only point is to make the thread pull all events, but implement the particular call to waitEventAndDispatch like you advise.

**Comment by rikkimax** [comment]
As long as you create and use a window fully on a single thread and never refer to it from another, you won't run into trouble on any platform.

Just got to make sure that happens here, otherwise a wrapper will be required, involving queues.

**Comment by p0nce** [comment]
For the minor problem of `waitEventAndDispatch` => ac7598a4c1598c3ea79b8428c3d4cf642228b648

**Comment by p0nce** [comment]
As for the other problem, namely that we pull events from another thread that the one that created it, well we don't control what threads from the host do, so launching a thread seems still necessary. Unless specific crashes can be traced back to that, we'll live with it.

**Comment by abaga129** [comment]
I realize I made a pretty foolish mistake here.  Looking at `x11window.d` it looks like the thread never terminates, which might be what is causing the crash when closing plugins in some hosts.

**Comment by p0nce** [comment]
To terminate the thread you can use an atomic for example.

What you can do is not to launch this thread if `listener is null` which is the current proxy for "this is a top-level window" (that makes window example a tool just for debugging with comments).

**Comment by detomastah** [comment]
@abaga129 is this issue still relevant?

**Comment by p0nce** [comment]
After discussion with @detomastah I feel like the only remaining problem is that in `WindowUsage.host` mode there still is a thread pulling events, instead of the caller.

**Comment by abaga129** [comment]
The plugins no longer cause hosts to crash, and multiple plugins can be open at the same time now.

**Comment by p0nce** [comment]
That remaining problem is not exactly critical.
