### ISSUE TITLE
dplug-build doesn't support custom target paths

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#252]
The build tool `dplug-build` doesn't support custom target paths defined in `dub.json`. Thus, it crashes on moving the built files, as it assumes them to be in the project's root directory.

This `dub.json` won't work:
```json
{
 "targetPath": "bin"
}
```

... and leads to the following error message: `error: myplugin.dll: The system cannot find the file specified.`

**Comment by p0nce** [comment]
That's a bug, dplug-build should find whatever dub produces.

**Comment by p0nce** [comment]
Fixed in 974f5d198da5f5899af30c962a16657f362c1bbc
