### ISSUE TITLE
Have a recommended way to debug interactively on macOS

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#254]
Interactive debugging is just nicer than lldb for plugin development (vs bugs), so if some user is primarily a Mac person he won't find Dplug pleasant.

**Comment by p0nce** [comment]
In other words : document the steps to have VSCode + native-debug extension by WebFreak001 work.

**Comment by p0nce** [comment]
https://www.kvraudio.com/forum/viewtopic.php?f=33&t=502679

**Comment by abaga129** [comment]
Actually this is a problem I've ran into recently too.  I'm on MacOS 10.12 Sierra and I havent had any luck with gdb.  I got lldb to work from the console but for whatever reason, I cant get it working with native-debug in VSCode.  If I figure it out, or if you have some information to help me get it working, I'll be more than happy to document it.

**Comment by p0nce** [comment]
Updated this page. https://github.com/AuburnSounds/Dplug/wiki/Getting-Started
