### ISSUE TITLE
Odd line in X11 Window

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#265]
https://github.com/AuburnSounds/Dplug/blob/master/window/dplug/window/x11window.d#L197

> alphaglosined: the & before _graphicGC looks to be wrong
> alphaglosined: even though it doesn't seem to actually affect it (oddly enough)
> p0nce: what would be the fix?
> alphaglosined: remove the &

**Comment by detomastah** [comment]
Here is the fix :) https://github.com/AuburnSounds/Dplug/pull/267
