### ISSUE TITLE
Custom client parameter types

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#288]
## Situation
The following example~~s~~ are taken from Dplug:
```d
double toNormalized(double value)
{
    return clampValue!double( (value - _min) / (_max - _min), 0.0, 1.0);
}
```

~~**Problem:** Basically nothing shown in the snippet above is not accessible from custom `Parameter` classes.~~

## Ideas
The following changes would be useful for custom `Parameter` type implementations:

Make `public`:
```d
T clampValue(T)(T x, T min, T max) {}
```

~~Make `protected`:~~

## Further notes
I don't know whether there are possible pitfalls with this changes.

**Comment by 0xEAB** [comment]
Another solution could be `protected @property` functions, so that the actual member access is wrapped.

**Comment by 0xEAB** [comment]
just realized a few of these properties already exist :see_no_evil: (will adjust inital message)

Nevertheless, one might consider to make `clampValue` public anyway.

**Comment by 0xEAB** [comment]
okay, half of the text is irrelevant now anyway (because I found out later that something was already possible, hence the edits).

So, the idea that is still left, is to change `dplug.client.params.clampValue` from `private` to `public`. So one can use it from within custom client Parameter type classes.

**Comment by p0nce** [comment]
We should rather replace with https://dlang.org/library/std/algorithm/comparison/clamp.html
This module was written at a time where `clamp` wasn't in the stdlib.

**Comment by p0nce** [comment]
Unless there is a problem with using `std.algorithm.clamp` but I don't remember if there was one.

**Comment by p0nce** [comment]
`min` and `max` are badly inlined and that's why I avoid them in Dplug in general, but Parameter code is only rarely time-critical so I'd rather delete `clampValue` instead of publicizing it.

**Comment by p0nce** [comment]
Hopefully breaks nothing 2542c954f3ede68f46e7ecc89cf5c735d7f37568
Removed `clampValue`.

**Comment by 0xEAB** [comment]
also an option. thank you for all the explanations :slightly_smiling_face:

**Comment by p0nce** [comment]
My pleasure
