### ISSUE TITLE
LV2 Client

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#307]
An LV2 client would be a nice addition since it is licensed under ISC and therefore a truely open/free standard.  I have begun work on LV2 on my fork of dplug.

What's Left
- [x] X11: Opens in separate window rather than widget (EDIT: superseded by #349 )
- [x] Crashes carla when opening GUI
- [x] Investigate why `--combined` needed for GUI to work
- [x] MIDI input (C source has been translated)
- [x] Implement IHostCommand properly for LV2Client
- [x] Write functions to generate manifest.ttl and plug_name.ttl files
- [x] Modify dplug-build to export .ttl files and package LV2 plugins
- [x] Allow for multiple descriptors
- [x] Investigate sample rate and how `resetFromHost()` should be called
- [x] Get TimeInfo from host
- [x] Remove pragma(inline) statements
- [x] Export descriptor function
- [x] Test on windows
- [x] Test on Mac OS
- [x] Change instancePtr to not be TLS
- [x] Generate descriptor at runtime
- [x] Implemented graphics mutex
- [x] Expose parameters as floats only (0..1 in range only)
- [x] Use float*[] for input/output ports rather than Vec!float[]
- [x] Parameter extraction
- [x] Preset extraction

**Comment by 0xEAB** [comment]
https://github.com/abaga129/dplug/tree/dev

**Comment by abaga129** [comment]
First major iteration is done and just needs review #313

**Comment by abaga129** [comment]
Now with #313 merged.  This is what's left to finish LV2

- [ ] Fix issues with rendering UI
- [ ] MIDI input (C source has been translated)
- [ ] Implement IHostCommand properly for `LV2Client`
- [ ] Write functions to generate `manifest.ttl` and `plug_name.ttl` files
- [ ] Modify dplug-build to export `.ttl` files and package LV2 plugins

**Comment by p0nce** [comment]
List of things from a cursory reading:
- [ ] Please remove any sort of `pragma(inline)`. At best it slow down things, at worst it will not build at all. This is not what `inline` mean in C++. `pragma(inline)` is the translation of "forced inlining" and forced inlining is almost always a bad idea unless one has measured and spent the time.

- [ ] relying on a TLS variable for `instancePtr` is a problem. TLS is forbidden in Dplug. It should be a `__gshared` variable at least, and even better it should go in some place that isn't a global else I'm not sure if multiple instance would work.

- [ ] in `LV2Client.activate`, initialize the client with 0 as `maxFrames`. This won't work, you need . It's better to call it in "run" than calling it in activate if you don't have a `maxFrames` there https://github.com/AuburnSounds/Dplug/blob/master/lv2/dplug/lv2/client.d#L211

- [ ] besides, the call should be to `resetFromHost` not `reset` https://github.com/AuburnSounds/Dplug/blob/master/lv2/dplug/lv2/client.d#L211

- [ ] in `LV2Client.run`, brand new `Vec` should not be created. Reuse them and use `clearContents` instead. Else the audio thread will call `malloc` every single buffer which is unacceptable. It can call malloc at initialization, but not all the time. `Vec` never so shrink back so `clearContents` + reuse + `pushBack` is guaranteed to amortize the calls.

- [ ] in `LV2Client.run` do not pass pointer to data will `releaseData`. This gives up ownership of the pointer, and the callee should call `alignedFree` on those, probably not what you wanted. https://github.com/AuburnSounds/Dplug/blob/master/lv2/dplug/lv2/client.d#L234

- [ ] graphics mutex lock is the responsibility of the LV2 client but is disabled https://github.com/AuburnSounds/Dplug/blob/master/lv2/dplug/lv2/client.d#L250 Use `makeUncheckedMutex` to create one.

- [ ] I think you should expose parameters as if they were Float only. This will avoid a lot of problems. The LV2 host doesn't need to know they are secretly int or bool.

- [ ] `setParameterFromHost` only takes 0..1 as input. Same remark than above. So a line like `_client.setParameterFromHost(port_index, cast(int)paramValue);` won't do what you think it does with an IntegerParameter that would have 3 possible values.

**Comment by p0nce** [comment]
- [ ] like `myLV2EntryPoint`, `lv2_descriptor` should call a template function taking `ClientClass` that return a descriptor stored in a `__gshared` global (this one is safe). Same for the UI descript, as one shared library contains one plugin I guess these descriptor can be shared across instances.

- [ ] Seem like LV2 doesn't have a way to expose several I/O configurations? 

- [ ] Seem like LV2 doesn't have a way to change sampleRate with the same created instance?

**Comment by p0nce** [comment]
Re: I/O, I asked on #lv2 @ freenode.net
```
<p0nce> how do you declare a LV2 plug that can do either 1-1 or 2-2 processing ? (mono => mono or stereo => stereo)
<p0nce> do you need multiple .ttl or multiple LV2_descriptor?
<rgareus> p0nce: multiple descriptors, yes.
<rgareus> p0nce: LV2, like VST2, (and unlike AU), has a fixed number of ports
<rgareus> so you basically create two plugins a mono and a stereo plugin.
<rgareus> however, if the plugin is LTI, you may just ask he host to replicate it for as many channels as needed.   It's mostly dynamic effects (e.g. compressors..) where channel-link matters
<p0nce> two plugins? you mean in different shared libraries? 
<p0nce> or multiple descriptors considered as two plugins by the host?
<p0nce> it seems it's the .ttl that describe the port, so if you are 1-1 and 2-2 you need multiple .ttl for each I/O arrangement?
<p0nce> as well as multiple descriptors?
<rgareus> p0nce: you can use a single .ttl and a single .so
<rgareus> just different descriptors for the 1-1 and 2-2 case.
<p0nce> thanks!
```

Re: samplerate change => the plug-in will be reinstantiated, hence `activate` called. An activate call should mark a boolean flag that `resetFromHost` has to happen in the `run` callback.
Seems like there is no synchronization needed between `activate` and `run`.

**Comment by abaga129** [comment]
Thanks for checking on that! I'll have a new PR coming soon that will address all of the issues you meantioned.  I was able to greatly slim down the `LV2EntryPoint` template simplify a lot involving ports.

The multiple descriptors I will probably put off until I start working on the changes to `dplug-build`.  After thinking about what rgareus said in your discussion it makes a lot of sense to me.  I think the `.ttl` files will be able to define multiple plugins with the same name as a bundle.  They will just need to have different URIs I believe.

**Comment by p0nce** [comment]
OK.

VST3 and AAX are designed to allow separate UI from DSP but in practice we do'nt support it in VST3 and AAX and many other plugin framworks also don't support it.

I'm all for cheating with __gshared, but keep in mind on POSIX there is only one `__gshared` variable by loaded dynlib so several plugin instance will share the same `__gshared` variable.*

So beware multiple instances!

You may use a `__gshared` map like in `dplug.core.map` if you need to map from something (what?) to LV2_Handle : it needs no initialization.

**Comment by abaga129** [comment]
I asked on #lv2 IRC about port configurations
> <drobilla> abaga129: Yes, and no, in that order, unfortunately
<drobilla> abaga129: Unless dyn-manifest counts, but you probably don't want to go there
<drobilla> abaga129: There are some vague ideas floating around about getting there without throwing the baby out with the bathwater, but that will be a long time coming if ever
<drobilla> abaga129: Why?
<abaga129> drobilla: Thanks for the answer.  I'm writing a wrapper for dplug and I figured I would check if there was away to expose port configurations from the plugin to the host rather than having to load the shared library and generate the necessary ttl
<abaga129> drobilla: dynmanifest looks like it is probably more than I'm wanting to do.  Dplug has a build tool that can load the shared library once it's built and extract the ports.

So it looks like we will have to extract that information from the shared library after it's built.

**Comment by p0nce** [comment]
TTL being generated internally looks unavoidable.

**Comment by abaga129** [comment]
Yes, it does.  We will have to extract presets the same way as AAX anyways.

**Comment by p0nce** [comment]
`maxFramesInProcess()` is only for buffer splitting and is only called from the "generic client" dplug.client.client.Client.
`resetFromHost` should be called with the maximum number of frames given by the LV2 host. There is probably one it gives.

(note: it's annoying everything is called "client")

**Comment by p0nce** [comment]
People on `#lv2` IRC suggest to announce here when ready :)
http://lists.lv2plug.in/listinfo.cgi/devel-lv2plug.in

**Comment by abaga129** [comment]
I think I've found why the UI isnt opening correctly.  I've been passing null for `parentInfo` in `openGUI`.  I didnt realize LV2 provides access to the parent window id.  I should be able to borrow some code from DPF
https://github.com/DISTRHO/DPF/blob/master/distrho/src/DistrhoUILV2.cpp#L389

**Comment by abaga129** [comment]
Update:
I have been working on this some.  LV2 Midi Input is working on my end.  I intend to fix the uri generation and get TimeInfo before the next big pull request.  I may try to fit in preset extraction as well.

**Comment by p0nce** [comment]
Small remark: in the ttl I see it references a X11 window. Should this change depending on the OS?

**Comment by abaga129** [comment]
Yes good catch.  I hadn't thought of that.  It should be a simple fix.
For mac there is
`ui:CocoaUI`
and windows
`ui:WindowsUI`

**Comment by p0nce** [comment]
- [x] RDF "Turtle" validation can be found here http://ttl.summerofcode.be/ and we already pass it
- [ ] seems like there is no support for `ui:binary` with spaces in paths
- [ ] more MIDI messages can be pass-through, it seems we don't need a translation layer (unlike VST3/AU)
- [ ] offset for MIDI input messages looks wrong

**Comment by abaga129** [comment]
> seems like there is no support for ui:binary with spaces in paths

Yeah, I was able to get it to work by using %20 in place of spaces in the manifest for the binary name and it worked in every host I tried except Carla for some reason.  I ended up changing dplug-build to remove the spaces from the binary name for LV2

**Comment by p0nce** [comment]
OK no problem then.

**Comment by p0nce** [comment]
RDF spec speaks of `\u0020` escape sequence instead of `%20` in IRI literals, HOWEVER I haven't seen any LV2 plugin that use those. Instead people use `-`and `_` it seems, and avoid special chars.

**Comment by p0nce** [comment]
32-bit does not seem possible on Windows, LV2 always assume native bitness, and there is no LV2 extension for this yet.

**Comment by p0nce** [comment]
To debug within Carla you have to rename the Carla binary to .zip and extract it. Else it is a self-extracting binary that is not as much easy to debug.

**Comment by p0nce** [comment]
- [ ] set parameter from host in `run()`
- [ ] time information in Carla

**Comment by p0nce** [comment]
LV2 has extensions to generate the TTL dynamically, so it may be suitable as an internal, untainted format for Dplug.

**Comment by abaga129** [comment]
When asking about generating the manifest in the #lv2 IRC channel, I was told that dynmanifest isn't supported by many hosts.

**Comment by p0nce** [comment]
- [ ] support set/get the whole plugin state, which avoids compatibility problem later on. DISTRHO show us the way to do it.
