### ISSUE TITLE
ALT + click => default position

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#309]
Alt + click should reset to default positions.

HY & Klanghelm also maintain the knob in default position through the drag, which seems to be a side effect.

**Comment by 0xEAB** [comment]
Isn't double-click to reset the more common way?

**Comment by p0nce** [comment]
Apparently both are expected!

**Comment by abaga129** [comment]
I was only aware of double-click also but im not opposed to it

**Comment by p0nce** [comment]
Switches don't reset to default on double-click, but do with ALT + click which can't be unintentional.
