### ISSUE TITLE
VST3 + Linux

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#319]
Bitwig and REAPER support it on Linux.
Doesn't load for now.

**Comment by abaga129** [comment]
Tracktion Waveform also supports it on linux.

**Comment by p0nce** [comment]
- [ ] enable back SMTG_SIZE_CHECK for linux 64b
- [ ] on linux, rename .so to .vst3

**Comment by abaga129** [comment]
I have dplug-build renaming from .so to .vst3 on linux now.  Reaper is recognizing the plugin but crashes when loading it.  I'll investigate why.

**Comment by abaga129** [comment]
Looks like it crashes at https://github.com/AuburnSounds/Dplug/blob/master/core/dplug/core/sync.d#L162

`handle` is null for some reason.

**Comment by abaga129** [comment]
I fear this is likely due to not supporting the XEmbed protocol.  I'm not sure how much work it will be to add this functionality.

**Comment by p0nce** [comment]
I guess we can abandon VST3+Linux for now?

**Comment by p0nce** [comment]
Uh I don't think there will be that much hosts on Linux for VST3.

**Comment by abaga129** [comment]
Yeah it may not be worth the extra work.  VST2 and LV2 seem to be the format of choice for Linux so maybe what we have is enough.

**Comment by xdave** [comment]
There's bitwig studio, too.

**Comment by abaga129** [comment]
Yesterday I fixed the issue that i introduced about drawMutex never being allocated and did a build. Reaper loaded the distort example but the gui wasnt being rendered correctly.  It may be as simple as handling xembed events in x11window.d.  I couldnt get bitwig to recognize it though.

**Comment by xdave** [comment]
Last time I looked at an example of this in the airwave vst code, there's a callback function for sending the xembed message when the editor is opened.

https://github.com/phantom-code/airwave/blob/master/src/plugin/plugin.cpp#L657

Called here:
https://github.com/phantom-code/airwave/blob/master/src/plugin/plugin.cpp#L389

**Comment by abaga129** [comment]
Actually that seemed to do the trick. I need to test a little more to verify.  I'll make a PR if its all good!

**Comment by abaga129** [comment]
PR #329 should fix all the issues.
