### ISSUE TITLE
Audio Hijack some AU plugins crash

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#324]
From the limited debugging I've been able to do, I've tracked it down to this assertion in dplug.au.client
https://github.com/AuburnSounds/Dplug/blob/master/au/dplug/au/client.d#L1699

Removing the assertion allows the plugins to load but obviously this is dangerous

**Comment by p0nce** [comment]
Need a git tag?

**Comment by abaga129** [comment]
Yes that would be helpful so I can update all of my plugins to the latest version

**Comment by p0nce** [comment]
This is v8.2.4

**Comment by abaga129** [comment]
Thanks!
