### ISSUE TITLE
dplug-build doesnt move binary for VST2 on linux

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#331]
This worked up until v8.2.8

In PR #329, I changed dplug-build to move the binary for VST3 and rename it to .vst3.  I forgot to add a check for if config is VST2 and to move the binary.  This is simple fix, but wanted to bring attention to it until it gets fixed.

https://github.com/AuburnSounds/Dplug/blob/master/tools/dplug-build/source/main.d#L586

**Comment by p0nce** [comment]
Should be fixed on master now!

**Comment by abaga129** [comment]
Thanks a lot!
