### ISSUE TITLE
can't build dplug-build

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#332]
#### Error message
```
dplug-build ~master: building configuration "application"...
source/main.d(591,30): Error: undefined identifier `configIsVST2`, did you mean function `configIsVST`?
ldc2 failed with exit code 1.
```

#### Link
https://github.com/AuburnSounds/Dplug/blob/v8.2.9/tools/dplug-build/source/main.d#L591

Also the comment next to the line appears to be wrong. The code names the file `.so`, not `.vst`.

**Comment by p0nce** [comment]
Fixed af7c2692a79ee9043f6c6be095e16040b5f693bd
