### ISSUE TITLE
Create a VST2 guide page in the Wiki

### ISSUE THREAD

**Issue by tekord** [AuburnSounds/Dplug#333]
Hi! I followed the Wiki which says:

```
Point a VST2_SDK environment variable to the matching VST2_SDK directory in the SDK.
Example: export VST2_SDK=/Users/MyName/vstsdk3610_11_06_2018_build_37/VST_SDK/VST2_SDK
```

I downloaded SDK from Steinberg's web site, opened terminal and set variable:

```
set VST2_SDK=D:\Packages\VST_SDK\VST2_SDK
```

and run build: `dub --compiler=dmd` from example project folder. I got the following errors:
```
dplug:vst 8.2.10: building configuration "library"...
..\..\vst\dplug\vst\translatesdk.d(9,42): Error: file "aeffect.h" cannot be found or not in a path specified with -J
..\..\vst\dplug\vst\translatesdk.d(9,64): Error: file "aeffectx.h" cannot be found or not in a path specified with -J
..\..\vst\dplug\vst\client.d(112,13): Error: undefined identifier AEffect, did you mean variable _effect?
...
```

I also tried to set VST2_SDK to public.sdk\source\vst2.x where header files are actually located, but it failed.

**Comment by 0xEAB** [comment]
The environment variable should point to the directory that contains the `pluginterfaces` (+ the `public.sdk`) folder.

**Comment by 0xEAB** [comment]
> I also tried to set VST2_SDK to public.sdk\source\vst2.x

The `public.sdk` folder doesn't contain the VST2 plugin-interfaces (`aeffect.h` + `aeffectx.h`). They're in the `pluginterfaces` one.

**Comment by 0xEAB** [comment]
> and run build: `dub --compiler=dmd` from example project folder

It's recommended (and for some plugin formats even required) to build your plugins using the [dplug-build](https://github.com/AuburnSounds/Dplug/tree/master/tools/dplug-build) build-tool.

**Comment by 0xEAB** [comment]
> ```
> set VST2_SDK=D:\Packages\VST_SDK\VST2_SDK
> ```

Please note that CMD's `set` command only sets the variable for the current CMD session (<- current console window, session ends by closing it).

**Comment by p0nce** [comment]
Hello,
It could be that you have a version of the VST SDK that doesn't include VST2 anymore.

The latest versions of the VST SDK don't include the VST2 headers anymore. You may have to find them otherwise, and also get a signed agreement with Steinberg in order to distribute such VST2 plugins if need be.

Dplug cannot redistribute such headers because Steinberg would emit a DMCA request.

**Comment by tekord** [comment]
Thank you all! I was very helpful. You should add some notes to wiki :)

**Comment by p0nce** [comment]
yes, will do !

**Comment by 0xEAB** [comment]
> It could be that you have a version of the VST SDK that doesn't include VST2 anymore (since this summer).

iirc, `vstsdk3610_11_06_2018_build_37.zip` is the final release containing the VST2 plugin interfaces.

**Comment by 0xEAB** [comment]
https://github.com/AuburnSounds/Dplug/wiki/Dplug-VST2-Guide

**Comment by p0nce** [comment]
Whoa, thanks @0xEAB !

**Comment by 0xEAB** [comment]
no problem :slightly_smiling_face:
