### ISSUE TITLE
AudioUnit view name is annoying to hear in screen readers

### ISSUE THREAD

**Issue by admiralbumblebee** [AuburnSounds/Dplug#340]
<img width="1151" alt="screen shot 2019-02-21 at 12 18 41" src="https://user-images.githubusercontent.com/607281/53188688-f10c5680-35d3-11e9-9acf-801ae7240224.png">

As shown in attachment.

macOS 10.14.2 - Logic 10.4.4

**Comment by p0nce** [comment]
Why is it incorrect? That name is generated at runtime, but it's not really common to generate this at runtime, I think only Blue Cat managed to do it too.

**Comment by p0nce** [comment]
Meaning "not pretty", it looks like a bug

**Comment by p0nce** [comment]
and is impractical for accessibility like screen readers

**Comment by p0nce** [comment]
> can't it at least be "Couture_UUID-here"

**Comment by p0nce** [comment]
Some vendors manage to have a human-readable class name, wondering how it works.

**Comment by p0nce** [comment]
That was fixed in Logic 
![Screenshot 2020-11-07 at 02 11 51](https://user-images.githubusercontent.com/1067485/98427783-d5dec480-209e-11eb-8994-4ef73b46a8bc.png)
