### ISSUE TITLE
X11 window parenting

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#349]
Left-over from #307 , not sure where we are exactly.

**Comment by abaga129** [comment]
#348 Fixed the window parenting issue.  X11Window now only uses XEmbed if it is built as VST3.  The `XReparentWindow` call was what was causing the issue for LV2 and VST2 in carla and qTractor.  X11 still has the issue of sometimes being distorted when opened, and has the flickering on flat-widgets.  I should probably open a separate issue for these problems though.

**Comment by p0nce** [comment]
Yes, please! This indicated a "race"-like condition with dirty rects and x11window, often quite hard bugs (traiditionally the hardest Dplug bugs)

**Comment by p0nce** [comment]
Superseded
