### ISSUE TITLE
Apple now requires notarization

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#358]
https://developer.apple.com/developer-id/

**Comment by p0nce** [comment]
> Chris: Plugins don’t need to be notarized; only stapled. Installers (which are technically apps) and DMGs need to be notarized.

> Drow: If you build an app (which we do but other plugin devs could also have apps such as standalone versions and download or authorisation managers), have DMGs or pkg installers, all of these need to be notarised.

**Comment by p0nce** [comment]
Probably going to open a new can of worms.

**Comment by p0nce** [comment]
Requires to upgrade to a 10.9+ macOS SDK, hence a breaking change.

**Comment by 0xEAB** [comment]
Does this only affect Dplug's pkg installers feature, or audio plugins, too?

**Comment by p0nce** [comment]
This only affects plugins built with `--installer`, on macOS starting with 10.14.5. I'm not sure there is any adverse effect on sales yet.

**Comment by abaga129** [comment]
What does a user on 10.14.5 see when installing a `.pkg` that isnt notarized?

**Comment by p0nce** [comment]
@abaga129 It is said to be like this, haven't updated yet https://www.kvraudio.com/forum/viewtopic.php?p=7199142#p7199142

**Comment by p0nce** [comment]
```
So I've just spent the better part of a day trying to get the notarisation service to work programmatically as part of our CI. I think I've done this now and the process is relatively  straightforward once you've pushed your way through all the gotchas.
The main takeaway I have is that the "hardened runtime" stuff isn't really to do with how you build your app, it's part of the signing process so you can do it all after your standard build wit some additional codesign flags.
Also, for our 60MB installer package, the service takes about 2-5mins to complete once uploaded to Apple so it's definitely possible to run as part of CI
The final point of interest (which I'm still not 100% sure if it's worked) is that once you've notarized the installer with Apple, you only need to staple the installer. I think this means that the certificate is simply read and cached by end-user machines and recalled when the actual app is run. I've not tested this yet though
```

**Comment by p0nce** [comment]
```
As far as I can tell, you only have to do it to the final pkg as long as it’s a “flat package” and you specify the “—deep” option.
codesign will drill down to every executable in the package (including those in the .app bundle) and create a signature for them.
I think the idea is that this creates a certificate on the Apple servers. If the user installs your pkg then it will look to Apple for a corresponding cert. If it doesn’t find one, then it will fail to install.
The (optional) staple process basically grabs a copy of the cert and distributes it with the pkg so offline machines can still install.
The one caveat to this that I’ve seen is if you’re distributing a kernel extension. For this, the individual elements need to be signed separately. But from what I can tell this requirement is considered a bug and will hopefully be resolved soon
The other thing is I don’t think dylibs (like plugins) need to be notarised, but dmgs and installers do so the process is basically the same.
```

**Comment by p0nce** [comment]
At least one other vendor distributes .pkg in a ZIP file, and notarize the .pkg file only.

**Comment by p0nce** [comment]
Proper upload command
`xcrun altool --notarize-app -t osx -f builds/Panagement-2-FREE-2.0.0.pkg -u <Apple ID> -p <app-specific password> --primary-bundle-id com.auburnsounds.somethingmoreorlessuniqueforthatbuild`

**Comment by p0nce** [comment]
Then to get the notarization output log:
```
xcrun altool --notarization-info <request ID> --username <Apple ID> -p <app-specific-password> -output-format xml
```
This gives a XML, which contains a URL, which give a JSON file, with proper errors. Yay.

**Comment by p0nce** [comment]
- [ ] AAX bundles are not signed correctly

Likely the same problem as Oli: "Developer ID Application:" vs "Mac Developer:" as the OSX identity. It seems our AAX are badly sign.

(Also the word on the street is that Eden 5 might be necessary, but I'm not sure.)

**Comment by p0nce** [comment]
- [x] `dplug-build` uploads to server
- [ ] `dplug-build` polls notarization servers
- [ ] `dplug-build` staple the installer

**Comment by p0nce** [comment]
Done
