### ISSUE TITLE
dplug-build crashes while extracting manifest on Windows with ldc

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#362]
Using latest dplug-build and ldc2 v1.15 dplug-build crashes when it gets to the extract manifest step.

DMD seems to work fine however.

## Output from dplug-build

```
entropy 2.6.2+commit.2.g4b224f7: building configuration "LV2"...
   Creating library .dub\build\LV2-debug-windows-x86_64-ldc_2085-125E1E27155D4C8307672796CE5C906A\entropy.lib and object .dub\build\LV2-debug-windows-x86_64-ldc_2085-125E1E27155D4C8307672796CE5C906A\entropy.exp
To force a rebuild of up-to-date targets, run again with --force.
Invalid source/import path: E:\PluginDev\dplug\$VST2_SDK\pluginterfaces\vst2.x
    => Build OK, binary size = 2.2 mb, available in ./builds/Windows-64b-LV2

*** Extract LV2 manifest from binary...
PS E:\PluginDev\entropy>
```

`dplug-build` crashes but doesnt give any output of why.  If I run it inside a debugger I'm able to see that it throws an exception in `GenerateManifestFromClient`, but I haven't been able to determine which line it happens at yet.

**Comment by p0nce** [comment]
Is it related to changes in runtime initialization?
Can be a crash inside the plugin too, in which case you can add output logging inside the LV2 exported function

**Comment by p0nce** [comment]
Sounds like the first GC use throws because the runtime isn't initialized, but it used to work so maybe something changed in LDC.

**Comment by abaga129** [comment]
> Can be a crash inside the plugin too

It's possible.  I tested with two of my own plugins. I will try it with one of the example plugins, and I'll try enabling logging too.

> Sounds like the first GC use throws because the runtime isn't initialized, but it used to work so maybe something changed in LDC.

That was my first guess as well.  I've tried running it with the runtime disabled in `GenerateManifestFromClient`, but had the same result.

Is there a good way to debug `dplug-build` on windows? I've been using GDB but It doenst show me where the exception is thrown.

**Comment by p0nce** [comment]
Mmm I usually debug from VisualD, but it depends if you want to step into dplug-build (A) or the plugin itself (B). I think there is no simple way to do both at once.

For (B) you can generate a plug-in solution with DUB, from VisualD choose dplug-build as host, and then you can step into the plugin. It the exception is not see at throw, it can be your exceptions options, or it can be that you have to use another debugging engine. It doesn't always work. There is wiki entry about debugging in case this is too time consuming to get it to work.

**Comment by abaga129** [comment]
Starting `dplug-build` from VisualD did the trick thanks!  The offending section is in `ttl.d`
https://github.com/AuburnSounds/Dplug/blob/master/lv2/dplug/lv2/ttl.d#L338

I'll investigate what is going on here, but looking at the string r being built, it definitely isnt right. I'm getting `"<T�U��Djr�p���ـ����nhancedStereoDelay.lv2/CutThroughRecordingsEntropyII-EnhancedSter�C��D���D0����C��D����ٲ�#r�����ٰ���٠����5�U��D���D�C��D������#r������0���������������ـ[R�D@�Fr�@�Fr��Fr�b"...`

**Comment by abaga129** [comment]
It isn't just my own plugins that have this issue.  Distort also throws an exception in `escapeRDF_IRI`
The windows showing the exception says `First-chance exception: 0xc0000005: Access violation`

**Comment by abaga129** [comment]
I think the problem is from `binaryFileName`.  It shows an absurd length when inspecting it in debug mode.

**Comment by p0nce** [comment]
Two possible solutions:
- perhaps characters >= 128 should also be discarded, as they are part of a UTF-8 sequence that won't be correctly interpreted by hosts?

- Or we could preserve wider UTF-8 charaters. This loop iterates by `char` (codeunit) instead of `dchar` (codepoint) because of `@nogc nothrow` concerns,  but it could iterate by dchar, using auto-decode or `.byDChar`.

**Comment by abaga129** [comment]
Something interesting that I've found is that the parameters passed to `GenerateManifestFromClient_templated` seem to be different between 32bit and 64bit on Windows.  

With 32bit using destructatorizer as an example: 'binaryFileName' has a length of 30 and `buildDir` has a length of 55.  

With 64bit: `binaryFileName` has a length of 770693912288 and `buildDir` has a length of 140706689274244

**Comment by p0nce** [comment]
Mmm in this case it sounds like some kind of ABI problem, the callback perhaps has different signature in `dplug-build` and in the LV2 client. It can be either a different parameter list, or a different calling-convention (`extern(Stuff)`).

**Comment by p0nce** [comment]
I think it's this line:
```
extern(C) alias generateManifestFromClientCallback = void function(const(ubyte)* fileContents, size_t len, const(char)[] buildDir);
```
maybe the alias is extern(C), but not the function.

```
alias generateManifestFromClientCallback = extern(C) void function(const(ubyte)* fileContents, size_t len, const(char)[] buildDir);
```

**Comment by abaga129** [comment]
Changing this line doesn't seem to have any effect unfortunately.  Something I've just found though is that I dont experience this on my other computer also running Windows 10.

The machine experiencing the bug has an AMD Ryzen CPU and the working machine is an Intel i5.  I wonder if it could have any effect.  I installed the same version of ldc2 (1.14) on the machine that isnt working to make sure that it isn't something introduced by ldc2 v1.15.

**Comment by p0nce** [comment]
It's very unlikely to cause any problem no.
It could be something brought by flags change in a ldc version

**Comment by abaga129** [comment]
Okay I will do some more investigating when i get a chance.
Is it possible that it is related to MSVC?  I plan to check the version for MSVC on both machines.

**Comment by p0nce** [comment]
Eh I don't know. Could be. Until you step debug into it it will hard to diagnose. I'm sorry I lack the time to help investigate.

**Comment by abaga129** [comment]
I completely understand.  I'll work on it and post my findings here.

**Comment by p0nce** [comment]
Is this a blocker for your release?

**Comment by abaga129** [comment]
Currently it isnt.  I'm holding off on LV2 for windows and MacOS until I can look at it further.  If absolutely necessary, I can use my other machine to release Windows LV2.  If you want to close this for now that's fine with me.  I can reopen it when I get a chance to look at it more :)

**Comment by 0xEAB** [comment]
> close this for now
> reopen it

I'd just keep it open…

**Comment by p0nce** [comment]
Yes, the policy I've been doing until now is to never close a bug until it is dealt with.

**Comment by abaga129** [comment]
I've started working on converting the ttl generation to be `@nogc`.  I decided to just use malloc and c-style strings instead of trying to write a `@nogc` string implementation.  It all seems to be working fairly well, however I wanted to ask how `escapeRDFString` works.  

```D
/// escape a UTF-8 string for UTF-8 RDF
/// See_also: https://www.w3.org/TR/turtle/
string escapeRDFString(const(char)[] s)
{
    string r = "\"";

    foreach(char ch; s)
    {
        switch(ch)
        {
           // escape some whitespace chars
           case '\t': r ~= `\t`; break;
           ...
           default:
               r ~= ch;
        }
    }
    r ~= "\"";
    return r;
}
```
I don't understand what the line `case '\t': r ~= `\t`; break;` actually does.  If I'm using const(char)[] instead of string is there any need for this escape then?

**Comment by p0nce** [comment]
Aha, indeed not very clear when reading. i also thought it did nothing. Maybe put a comment there!

`case '\t': r ~= `\t`; break;`

The case is matching **one** TAB character, and produces **2** characters `\` and `t` (the letter).
This is because in D, you can have string literals in various forms.

- Regular double-quote literals:
  `"normal string literal with escaping \n"`

-  character literals
`'a', '\\' character literal`

-  **backquote strings** that don't understand escaping:
``  `im a special string that don't have \n escaping` ``

See also: https://dlang.org/spec/lex.html#string_literals

**Comment by abaga129** [comment]
Ah of course! I didnt realize that strings using `\`` were treated differently!  Should be straightforward to do the same using a char array.  I should be making a PR to close this within the next day or so.

Thanks for the explanation!

**Comment by p0nce** [comment]
snprintf is your friend!
