### ISSUE TITLE
Installer icon conflict between Windows and macOS

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#375]
Windows installers rely on a `.ico` icon while macOS installers rely on `.png` for the icon.  This causes a conflict when producing installers for both platforms.

I propose we have two separate fields `iconPath-windows` and `iconPath-osx`.  I'm happy to make a PR for this.

**Comment by p0nce** [comment]
OK for me!

**Comment by abaga129** [comment]
PR opened!

**Comment by p0nce** [comment]
The fix is in  v8.4.13
