### ISSUE TITLE
/licenses.json

### ISSUE THREAD

**Issue by fpesari** [AuburnSounds/Dplug#380]
Hello,
right now, checking license for files is a bit discouraging, since you have to look at every file.

Having a file called `licenses.json` in dplug's root directory which contains this data:

```
{
...,
"client/dplug/client/binrange.d": "Boost License 1.0",
...,
}
```
Would make things much clearer for both developers and packagers.

I would contribute such a file myself, if necessary - you can automate most of the work by using `grep` but doing it by hand ensures there are no mistakes.

**Comment by p0nce** [comment]
I would certainly not want to maintain this, and I don't see the problem since license stuff you need to know will be in the Wiki. https://github.com/AuburnSounds/Dplug/wiki/Binary-redistribution-licensing-requirements
