### ISSUE TITLE
AAX signed improperly

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#381]
Caught by notarization.
Other formats pass notarization, including AU with component manager!

**Comment by p0nce** [comment]
Is it possible to get this issue diagnosed without notarization?

**Comment by p0nce** [comment]
OK, everything solved if `"developerIdentity-osx"` is set to just the Apple Dev ID such as `"H7DW761TY2"` (use your own). It also make the login popup disappear :)

**Comment by 0xEAB** [comment]
This should probably get documented in the [Wiki](https://github.com/AuburnSounds/Dplug/wiki/Dplug-AAX-Guide).

**Comment by p0nce** [comment]
Done. Also updated example in dplug-aax
