### ISSUE TITLE
FLStudio + AU Component API => not listed

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#389]
+Audio Unit
We probably fail FLStudio validation.
Reported by @abaga129

**Comment by p0nce** [comment]
Reproduced, we are indeed unlisted.

**Comment by p0nce** [comment]
Doesn't call into the AU, so maybe similar to why iTerm2 doesn't see AU outside Apple sometimes.

**Comment by p0nce** [comment]
Plugin is visible iff dplug-build supports Component Manager API but not Audio Component API.

**Comment by p0nce** [comment]
Does FLStudio Mac recognize any other AU plugin using the Audio Component API?

**Comment by p0nce** [comment]
Dplug plugins appear in the FLStudio plugin manager with an empty Name, status ok

**Comment by abaga129** [comment]
This may not be useful information but Dplug Audio Units built before the Audio Component API show up in FL Studio but cannot be loaded.  Is there anything I can do to help?

**Comment by p0nce** [comment]
Well I was thinking about putting this bug on hold for the moment.
The reason being that FLStudio Mac is less likely to be used, and VST and VST3 versions do seem to work in FLStudio Mac.
It is not impossible that FLStudio + Audio Component API is buggy and go through the Component Manager every time (that's what it does for Voxengo who lacks the Audio Component API).
- [ ] To be sure I need to check Kotenikov but deleting its .rsrc

**Comment by p0nce** [comment]
Maybe it was the dplug:gui race fixed recently.

**Comment by p0nce** [comment]
Dupe of #501

**Comment by p0nce** [comment]
Still very current, QA says "Does not load with FLStudio + AU"

**Comment by p0nce** [comment]
No problem anymore as of Panagement 2.4 + FLStudio 20.8.4 + macOS in arm64, so the problem is probably fixed from the other end.
