### ISSUE TITLE
Need static runtime for Linux

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#391]
Tester reports:

> com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 2 plug-in AuburnSoundsPanagement2.so: libphobos2-ldc-shared.so.87: cannot open shared object file: No such file
libphobos2-ldc-shared87 is not available via apt, I can install this manually but I'm not sure if that's the process that you want for your users
latest phobos2 available is 78

DMDFE 2.078 corresponds to LDC 1.8.0, which means eventually stuff on linux worked by happy coincidence?

**Comment by abaga129** [comment]
Are you building with LDC or DMD?  DMD links against static runtime for me.  LDC however does not.  It's been on my list to look at but low priority

**Comment by 0xEAB** [comment]
I'd advice to stay away from distro-dependant stuff here. Those will usually be pinned to one specific version varying from distro to distro, version to version. Not to forget to mention custom vendor specific patches.

We should also check whether vanilla LDC as packaged by the LDC team uses static or dynamic runtime linking per default. For distro-packaged stuff it'll usually be dynamic, as intended by their design.

**Comment by p0nce** [comment]
`-static` fails with:
```
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/4.9/crtbeginT.o: requires dynamic R_X86_64_32 reloc against '__TMC_END__' which may overflow at runtime; recompile with -fPIC
```
Not sure why.

**Comment by p0nce** [comment]
Something that seems to work is erasing `libphobos2-ldc-shared.so` and copy  `libphobos2-ldc.a` to `libphobos2-ldc-shared.a` . Same with druntime

**Comment by p0nce** [comment]
- DMD works as intended. It all probably works because we want to link with this library but do not actually jump into it (it isn't -fPIC unless I'm mistaken)
- `-static` wants to link to the C runtime statically too, which isn't useful
- `-shared` flags always append `-shared` to linked default libs which is ultimately the problem

Currently on Linux we do depend on:
```
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libphobos2-ldc-shared.so.87]
 0x0000000000000001 (NEEDED)             Shared library: [libdruntime-ldc-shared.so.87]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

- [ ] try not to link upon phobos and druntime...

**Comment by p0nce** [comment]
Reported here https://github.com/ldc-developers/ldc/issues/3168

**Comment by p0nce** [comment]
- [ ] Does the LDC developers solution work?
