### ISSUE TITLE
Put Linux VST3 in a bundle

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#397]
A tester report the new binaries (with static runtime) not scanning, rather than crashing at load.

**Comment by p0nce** [comment]
Sometimes work, apparently it depends on what packages are installed.

**Comment by p0nce** [comment]
Actually = Bitwig doesn't see the Auburn Sounds VST3 plug-ins, but see the VST3 plug-ins.

**Comment by x42** [comment]
The problem seems to be that the linux VST3 are
(a) not in a bundle
(b) expose `initDLL` and `ExitDll` as entry/exit symbol. Those are for Windows only. On Linux it should be  `ModuleEntry` and `ModuleExit`

**Comment by p0nce** [comment]
Good point, thanks ! I'm surprised by (a) because it wasn't necessary in Mac and Windows AFAIK

**Comment by x42** [comment]
As far as I can tell, on MacOS a mach-bundle is also required. It's only Windows were VST3 can be a .dll by itself (although recently they're also preferably packaged into a folder structure).

**Comment by x42** [comment]
The bundle is likely only a secondary issue. However it's still prudent to follow  https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3loc.html

The entry-methods are the crux. For whatever reason they're different on MacOS/X, Linux and Windows.   `grep Func module_*` in  https://github.com/steinbergmedia/vst3_public_sdk/blob/master/source/vst/hosting/

**Comment by p0nce** [comment]
Thanks again, this helps a lot.

As for whether we should put the VST3 in a directory with additional files, my policy until now has been to wait until some hosts don't support the legacy way.

The problem with directories is that people that install these plugins manually sometimes copy the file inside the bundle, instead of the bundle. Most Dplug plugins are supposed to have installers, but on Linux they don't (yet). Before installers we've quite a few macOS users copying the content of the bundle instead of the bundle...

This problem is much more likely imho than the problem of hosts breaking compat', but of course if someone step up and want to implement that it's always open :)

**Comment by p0nce** [comment]
Adding the Linux entry methods didn't help on Linux + Bitwig + VST3 (aca318cb75af7b54d16bcc0f3ab4f21f34258073), so most likely it is that bundle requirement.

**Comment by p0nce** [comment]
For Bitwig to see the plugin, it must be in a bundle and the final executable must be a .so

**Comment by p0nce** [comment]
OK, the crash is in X11 in both reaper and bitwig, it's a VST3 + Linux regression
