### ISSUE TITLE
Linux builds needing too recent shared libraries

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#406]
@abaga129 saw the error:
> swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/reker/.vst/libusing-runtime.so

That's because the build machine has more recent libm than test machine.

How to avoid that?

**Comment by p0nce** [comment]
Yup, that's what I was thinking... How are you supposed to link against 2.24 dynlib? Maybe we can make our executables all static, but in that cas I had -fPIC problems.
Or use ancient linux?

**Comment by abaga129** [comment]
We could build a docker container with dplug-build and ldc2 on Ubuntu 16.04 (glibc 2.23) and use it for builds.  Then we would only support Linux with glibc >= 2.23.

**Comment by p0nce** [comment]
Very interesting! Possibly this is just about saying that to the CI then. Perhaps such a vm already exist in Azure.

**Comment by abaga129** [comment]
Yeah that was my thought too! It would provide a stable build platform for linux binaries.  There is https://hub.docker.com/r/dlanguage/ldc but it has ldc 1.9.  We could fork this or build our own container with ldc 1.17 and dplug-build installed.

**Comment by p0nce** [comment]
LDC 1.17 is only needed for Catalina (and I'm not even sure). 1.9 should work too with Dplug v9 IIRC.
