### ISSUE TITLE
Please separate core/dplug/core/nogc.d

### ISSUE THREAD

**Issue by aferust** [AuburnSounds/Dplug#407]
Is there any possibility to have core/dplug/core/nogc.d as a separate package on dub package registry?

**Comment by p0nce** [comment]
What's the problem exactly with depending on `dplug:core`? If you want dplug:core then you are probably making shared libraries and might want more goodies like that no?

**Comment by aferust** [comment]
I am sorry, I didn't do my homework well before opening the issue :) I thought VST licence is applied to all subpackages. Now I realized that dplug:core has boost licence. I am planning to use some functions in core.nogc for [opencvd](https://github.com/aferust/opencvd) to avoid GC allocations.

**Comment by p0nce** [comment]
OK. 

Something to keep in mind if using `mallocNew` and `destroyFree` is that if you do want to track the members lifetime through GC (if the runtime is enabled), then you have to add GC roots in case it is needed to keep traceability.
See also emsi-allocators for a function that tells whether an allocated objects need to register GC roots.https://github.com/dlang-community/containers/blob/931aad7fbcdfa19ca267a854ef76b94c3a609a12/src/containers/internal/node.d#L60

**Comment by aferust** [comment]
Thank you for clarification and awesome library. I will keep it in my mind. So far I have only used: mallocSliceNoInit!T, mallocDup, and Vec!T in core.vec also. Things are just working for now in [opencvdgogc](https://gitlab.com/aferust/opencvdnogc).
