### ISSUE TITLE
Docker container for linux CI builds not using latest dplug-build

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#414]
I think the easiest solution will be:
-  Have the docker container have a clone of the git repository stored in it
- Have the container keep a symlink from dplug/tools/dplug-build/dplug-build to /usr/local/bin/dplug-build
- Run git pull on the repo before each `docker run`
- Run dub on dplug/tools/dplug-build

That way we will always have the latest.  We could also allow the docker container to accept a special parameter when running to specify wether or not to update dplug-build.

**Comment by p0nce** [comment]
I'd also like to investigate static linking the whole executable.

**Comment by p0nce** [comment]
I met someone from Linphone who deals with the desktop app, and he says for Linux distribution (they use a RPM) what they do now is build on Ubuntu 16 so that glibc version is more compatible. Maybe Azure has that option already?

**Comment by p0nce** [comment]
It seems to me all we need to do is: 
```yaml
vmImage: 'ubuntu-16.04'
```
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

**Comment by p0nce** [comment]
And this would make #408 unneeded?

**Comment by p0nce** [comment]
Done in 0eb2220abbefedc06e458caea7fa0cb110fa1076
