### ISSUE TITLE
x11 with flat-widgets regression

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#421]
I believe there may have been a regression in the recent X11Window rewrite.  I've noticed in more than one of my plug-ins that I'm now experiencing a "flickering" effect.  The controls are also very unresponsive.

The best way to show it is with a gif
[M4 Mutliband Comp](https://media.giphy.com/media/RghXLusArrfLASf7VR/giphy.gif)

This looks fairly similar to #350

**Comment by p0nce** [comment]
I get a 404 error with https://media.giphy.com/media/RghXLusArrfLASf7VR/giphy.gif
This is absolutely possible, I want to look into it what could happen, any way to repro with perhaps ClipIt?

**Comment by p0nce** [comment]
https://cdn.discordapp.com/attachments/326372116309999616/645075625111191565/dplug-regression.gif

**Comment by abaga129** [comment]
Odly enough I can't seem to reproduce this bug in ClipIt.  Also through testing I've found that this regression started in v9.0.13.

Since I can't reproduce it in ClipIt, here is a clip of the regression in  [POP Sound Shaper](https://github.com/ctrecordings/POPSoundShaper) which is at least open source.
https://cdn.discordapp.com/attachments/326372116309999616/645100252029780018/pop_sound_shaper_regression.gif

**Comment by p0nce** [comment]
Reproduced using :
```
#!/bin/sh
dplug-build --compiler ldc2 -c VST
cp builds/Linux-64b-VST/Cut\ Through\ Recordings\ POP\ Sound\ Shaper.so ~/Plug-Ins/VST2/Cut\ Through\ Recordings\ POP\ Sound\ Shaper.so
reaper
```

(unrelated, the LV2 of Pop Sound Shaper doesn't seem to load, and dplug-build crash at the end of generating it)

**Comment by p0nce** [comment]
Found #422 which is not the main problem.

**Comment by abaga129** [comment]
Thanks!  I'll have to look into why LV2 doesn't work with POP Sound Shaper.
