### ISSUE TITLE
dplug:vst should build without VST2 SDK, when VST2 is not the target

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#437]
This create hassle for new DPlug users since `the VST configuration is default.

- [x] make VST3 the default configuration, make examples all support VST3
- [x] hide the VST2Client if version identifier `VST` isn't defined
- [x] if `VST2_SDK` is not defined, `dplug-build` should set it to an invalid value `"invalid-dummy-value"` and give a warning that the VST2 version won't build
- [x] Update the getting started tutorial to always use `dplug-build` and VST3 as a starting point

**Comment by p0nce** [comment]
Indeed it's been a while since anybody has said "Dplug builded one plugin on first try", which was a strength before VST2 SDK was mandatory. So no new users probably due to that.

**Comment by 0xEAB** [comment]
How much of Dplug does depend on VST2?

**Comment by p0nce** [comment]
Just the VST2 client, it's just that by default a plugin that has `dplug:vst` in dependencies wants to compile this module even if the `VST` version identifier isn't defined.

**Comment by p0nce** [comment]
Done, tutorial updted too.
