### ISSUE TITLE
Panagement/CliptIt crashing on Arch Linux

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#439]
Probably Panagement-related but:

Panagement + LV2 + Arch + Ardour5 => crash after a few seconds

Panagement + LV2 + XUbuntu 18.04 + Bitwig => crash after a few seconds
> The plugin crashes all by itself after a few seconds. Repeatedly. Reload, wait perhaps 5 seconds doing absolutely nothing, then crashes.

**Comment by p0nce** [comment]
This is really looking like a bad fix inside Panagement.

**Comment by p0nce** [comment]
Lots of users are reporting normal function, except some on Arch mostly.

**Comment by p0nce** [comment]
https://forum.audacityteam.org/viewtopic.php?f=48&t=108249 Two reports of Audacity crash, this time with a trace.

**Comment by p0nce** [comment]
Bug with audacity reproduced:
``` 
 Most likely this is a multi-threaded client and XInitThreads has not been called
```
I just though XInitThreads was to be called by the host and not the plugin...

**Comment by p0nce** [comment]
I think our own mutex should go and we should use XLockDisplay / XUnlockDispla+ our own mutex (  in case XInitThreads wasn't called)
This way the plugin host still choose whether it uses XInitThreads or not.

**Comment by p0nce** [comment]
X11 Race regression fixed in v9.1.8. This fixed at least the Audacity crash. I suspect other crashes are due to the same race, but maybe with some Arch specifics, difficult to know without testing on Arch.

**Comment by p0nce** [comment]
Probably fixed since v9.1.8, should test when given the chance.

**Comment by 4ong** [comment]
How can I help with tests here? I use Arch

**Comment by p0nce** [comment]
Hello,

If you can build a LV2 plug-in using the latest Dplug ~master and it works in Ardour, I think will prove that Dplug plug-ins work on Arch.
You can follow the dplug tutorial here in the Wiki: https://github.com/AuburnSounds/Dplug/wiki/Getting-Started

**Comment by 4ong** [comment]
Ok, from what I've tried:
In Ardour / LV2:
- Destructatorizer works
- The plugin "CLIP It" could not be loaded
See the Log window for more details (maybe)

In Reaper / VST3:
- "CLIP It" crashes Reaper (segmentation fault)
- Destructatorizer works

I will try more tomorrow.
P.S. Thanks for the such a wonderful project (just found it today) it's really perfect to avoid C++/Rust for VST development!

**Comment by p0nce** [comment]
Hello,

Would it work with ClipIt if you comment out the `onDrawRaw` method? This part is basically a recent test for Canvas-like functionnality that is very recent.

Thanks for the praise :) We're trying to stay practical

**Comment by 4ong** [comment]
Without onDrawRaw - ClipIt works as VST3 in Reaper, but screen issue in Ardour (LV2).
![image](https://user-images.githubusercontent.com/13717891/80468646-bc1a3300-893f-11ea-97fb-438ee3a0cb86.png)

**Comment by p0nce** [comment]
Cool you found the same glitch as #467 !
Apart from the CliptIt crash (recent regression), #439 and #467 looks dupe.

**Comment by 4ong** [comment]
Ok, I'm still learning the internals of the Dplug.
But for now, I can help with testing on Linux/Windows with Reaper/Bitwig/Ardour

**Comment by p0nce** [comment]
Basically both bugs are the same it's a race condition in `window/dplug/window/x11window.d`, one of the "finer" part of the library.

**Comment by p0nce** [comment]
Found a bug with ClipIT + Ardour6 + LDC + LV2 + debug build 
- instantiate twice
- open/close one interface like crazy

**Comment by p0nce** [comment]
To fix it, XEvent from the dead window needs to be pulled from the queue manually before the other window can call XCheckEventWindow.

```
diff --git a/window/dplug/window/x11window.d b/window/dplug/window/x11window.d
index ba2dcf4c..493c8180 100644
--- a/window/dplug/window/x11window.d
+++ b/window/dplug/window/x11window.d
@@ -653,8 +653,19 @@ private:
         XFreeGC(_display, _graphicGC);
         freeBackbuffer();
         XDestroyWindow(_display, _windowID);
-        unlockX11();
 
+        // We need to flush all window events from the queue that are related to this window
+        // MAYDO: the right way would be to arguably terminate the event thread with the destroy event 
+        // instead of an out of band flag. But order of destruction would have to be checked for a bit of everything.
+        XSync(_display, false);
+        XEvent event;
+        while(true)
+        {
+            Bool found = XCheckWindowEvent(_display, _windowID, windowEventMask(), &event);
+            if (!found) break;
+        }
+
+        unlockX11();
     }
 
     // this frees _graphicImage

```
