### ISSUE TITLE
Windows installer doesn't find the right "Program Files" directory when localized

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#441]
> It will suggest to save the plugin in C:\Program Files (x86)\… when it should actually be C:\Programme\… (notice the localized “Programme”)

**Comment by abaga129** [comment]
Maybe we can use $PROGRAMFILES64 and $PROGRAMFILES32 as described [here](https://nsis.sourceforge.io/Reference/$PROGRAMFILES).  It's unclear if these variables take locale into account.
We should be able to just change the hard coded paths [here](https://github.com/AuburnSounds/Dplug/blob/master/tools/dplug-build/source/main.d#L27)

**Comment by p0nce** [comment]
https://stackoverflow.com/questions/9087538/is-programfiles-a-constant-declared-in-nsis-or-is-it-the-environment-variable-r

**Comment by p0nce** [comment]
Solved in v9.3.2
