### ISSUE TITLE
Deprecation: opCatAssign is deprecated.

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#447]
Many messages `Deprecation: opCatAssign is deprecated.` when building with DMD 2.088+
On recent D frontends, use the new method instead.

**Comment by abaga129** [comment]
I've been getting this as well. It looks like it's from appending parameters in `buildParameters()`.

**Comment by p0nce** [comment]
Do not hesitate to open issues even for small deprecation !

**Comment by p0nce** [comment]
This is v9.1.10

**Comment by abaga129** [comment]
Okay next time I wil! Thanks!
