### ISSUE TITLE
dplug:vst3 not building with LDC 1.20

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#451]
Follow-up issue from #450 , there were two separate problems.

**Comment by p0nce** [comment]
Not reproduced, using `Linux x220 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by p0nce** [comment]
Not reproduced, using Ubuntu 18.04 and LDC 1.20.0 x86_64

**Comment by m3m0ry** [comment]
Can confirm. I failed trying to reproduce it myself (on a different machine). It seems that the `ldc` package in debian is somehow broken. `ldc` package in ubuntu is ancient.

I recommend to install `ldc` directly from [releases](https://github.com/ldc-developers/ldc/releases)

**Comment by p0nce** [comment]
- [ ] modify the Wiki so that people pull LDC from the release page
