### ISSUE TITLE
X11 - Opening plugin with greater width or height than the monitor will crash the host

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#459]
One of my monitors is in portrait mode.  I noticed that if I have the host on this monitor, loading Convergence will crash the host.  It seems that Convergence is too wide (1000px) for the monitor.  This could be a problem for smaller monitors as well.  I'm assuming this is only X11 for now.  I'll have to test on Windows and MacOS.

**Comment by p0nce** [comment]
Works in Ardour 6 + VST2 + Convergence + 5.8.16-2-Manjaro

**Comment by p0nce** [comment]
@jpcima also didn't reproduce apparently. Shall we close it?

**Comment by abaga129** [comment]
This seems to have gone away. I haven't experienced it for some time so perhaps it was something specific to Convergence. I'll go ahead and close it.
