### ISSUE TITLE
ARM 32bit support

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#464]
Like #458 but **32 bit**.

Mainly interested in: `arm-linux-gnueabihf` (RPi; *armv7l*)

**Comment by 0xEAB** [comment]
- `../../core/dplug/core/nogc.d(480,9): Error: static assert:  "No debugBreak() for this compiler"`

    Maybe make this a template so it won't cause any problems as long as it's not used?
- `../../core/dplug/core/random.d(50,9): Error: static assert:  "Unsupported"`
    
    Could that work?
    ```d
    else version(ARM)
    {
        import std.datetime : MonoTime;
        
        result = cast(uint)(MonoTime.currTime.ticks);
    }
    ```

**Comment by 0xEAB** [comment]
Why does the *msencode* example compile in *dplug:cocoa*?

**Comment by p0nce** [comment]
> Maybe make this a template so it won't cause any problems as long as it's not used?
You can make it do nothing as a debug construct, until we find the equivalent.


> Why does the msencode example compile in dplug:cocoa?

I see dplug:vst3 depends on dplug:window I don't remember why. This sounds avoidable?

**Comment by p0nce** [comment]
> Could that work?
Possibly yes. It only depends if it needs the runtime or thread-local or static ctor. If not, it can be used.

**Comment by p0nce** [comment]
Note that `dplug:vst3` now doesn't depend upon `dplug:window`, however as it's an AU some of the AU code was originally in "Cocoa" or "Carbon" framework and as such the subpackages will be pulled.

**Comment by p0nce** [comment]
OK I got myself a Raspi however I'm not sure how to run unittests from this device? Ideally I would have a armv7l compiler targetting armv7l I guess.

**Comment by p0nce** [comment]
Epilogue:

> Raspbian itself provides a package for LDC

Supporting ARM 32-bit might be a bit involved, as there is no CI in Travis.
It isn't necessarily hard to do so though (minus the optimizations...).

**Comment by p0nce** [comment]
Dplug now compile with ARM 32-bit, you can build a working dplug-build, however `dplug-build` currently pass a wrong `-a x86_64` flag and should probably know a bit about ARM.

**Comment by p0nce** [comment]
Further work in #490

**Comment by 0xEAB** [comment]
neat :tada: thanks

**Comment by p0nce** [comment]
![2020-09-28-000428_1024x600_scrot](https://user-images.githubusercontent.com/1067485/94377004-7051fc80-011e-11eb-8cca-831a80864b12.png)

Was able to make the LV2 and VST2.4 work in Ardour.

The only thing it needs is a tweak to dub.json in order not to send `-fvisibility=hidden`, since the shipped LDC and DUB is old.

**Comment by p0nce** [comment]
Tutorial in https://github.com/AuburnSounds/Dplug/wiki/Release-notes
