### ISSUE TITLE
Ardour 5.12 + LV2 + Graillon 2.4 + Debian SID + x86_64 => visual glitch

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#467]
![image](https://user-images.githubusercontent.com/1067485/80411011-c4d12180-88cb-11ea-8a3f-f0294a74c9f5.png)

First draw is broken. Not sure how repeatable, happened for the user at first run.

**Comment by p0nce** [comment]
Since then 2 X11 bugs were resolved, let's check that.

**Comment by p0nce** [comment]
Still current!

**Comment by 4ong** [comment]
Manjaro (Arch), Ardour 5.12, LV2  - no glitches with a free version from the website
![image](https://user-images.githubusercontent.com/13717891/80426907-002d1980-88e7-11ea-8290-bfd3057f6284.png)

**Comment by p0nce** [comment]
@4ong also reproduced on Manjaro + LV2 + Ardour 5.12, but with ClipIt

![image](https://user-images.githubusercontent.com/1067485/80477333-102b1480-894c-11ea-80e7-440a1204009b.png)

Possibly it's timing dependent and happens only when drawing is fast

**Comment by p0nce** [comment]
Cannot reproduce the glitch with Manjaro + Ardour 6 + Clip It + LV2.

**Comment by p0nce** [comment]
Cannot reproduce the glitch with Manjaro + Reaper + (Panagement or Graillon latest release) + VST2.

**Comment by p0nce** [comment]
Not reproduced on Manjaro + Ardour 6 + Clip It + LV2 + Dplug from now. This seems to have disappeared.
