### ISSUE TITLE
Windows Uninstaller

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#492]
People can stumble upon solved bugs (such as #491) because we don't have an uninstaller, so installing a newer VST2 will not hide the old one, and this bug surface for hosts that use fixed paths as VST2 hosts.
Less of a problem on Mac because paths are fixed.

**Comment by abaga129** [comment]
If the user chooses the same path for VST2 when running a new version of the installer, will it not overwrite the old VST2?

It sounds like we need to set a registry key that contains the path to the VST2 so we can make sure it gets removed.

**Comment by p0nce** [comment]
At the same time, the problem will go away if we wait since VST2 will go away ^^.
But that is a request that has been answered some times (how to remove things), and two cases of wrong support for OBS Studio.

**Comment by 0xEAB** [comment]
> If the user chooses the same path for VST2 when running a new version of the installer, will it not overwrite the old VST2?

Maybe the new installer could run the previous uninstaller it finds on the system first.

**Comment by p0nce** [comment]
Added by @jpcima in #528
