### ISSUE TITLE
Graillon: please mark atom ports as connection optional

### ISSUE THREAD

**Issue by brummer10** [AuburnSounds/Dplug#495]
Would it be possible to mark the atom ports as connection optional, to allow the use in hosts which didn't support atom ports.
`lv2:portProperty lv2:connectionOptional ;`

I've edited the manifest.ttl file to check if they be optional connected, and it seems so.

**Comment by p0nce** [comment]
Sounds like a very good idea! Especially with (future) correct support latency for LV2.

**Comment by p0nce** [comment]
Latency output port and Event input port are now lv2:connectionOptional in ~master.

**Comment by p0nce** [comment]
6c56cff609579edf0b81997959337b9cf0bb4ad1
