### ISSUE TITLE
Installer unclear for 64-bit VST2.4

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#506]
Just had a report from Ableton 9 user on Windows. Such a user can only use the 64-bit VST2.4 format.

However he missed the relevant screen in the installer because it's probably not differentiated enough from the former (32-bit VST2.4), it's the same text and all.

**Comment by p0nce** [comment]
TODO: test with new installer

**Comment by jpcima** [comment]
A difference is that x86 does not get asked for x64 path, it will be skipped.
x64 will be like before.
Do you have a suggestion how it should be presented, such that it will be clearer?

**Comment by p0nce** [comment]
Here is the VST 2.4 screens:

![32-bit](https://user-images.githubusercontent.com/1067485/105616903-8de85780-5dda-11eb-8a74-c92dee0f3b8b.png)
![64-bit](https://user-images.githubusercontent.com/1067485/105616905-8f198480-5dda-11eb-809e-627826e01a2b.png)

**Comment by p0nce** [comment]
Here is the user report that prompted the Issue:

![image](https://user-images.githubusercontent.com/1067485/105616988-79f12580-5ddb-11eb-8da7-3f2dad5a8263.png)

**Comment by p0nce** [comment]
![image](https://user-images.githubusercontent.com/1067485/120485163-1e9bf900-c3b4-11eb-840b-0fd26cf406a1.png)
Unable to make bold text, but now 64-bit and 32-bit is inverted, and less text.
