### ISSUE TITLE
32-bit x86 + Linux + unittests => Program exited with code -11

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#520]

**Comment by p0nce** [comment]
Not sure if supporting that is worth it

**Comment by 0xEAB** [comment]
*-11* might be a null dereference

**Comment by p0nce** [comment]
I think I was mistaken. I've seen this error with Github Action but with the intel-intrinsics repo. The same tests work on Windows x86 32-bit in GA. So as neither Dplug nor intel-intrinsics really support Linux x86 32-bit, I think we could close?
