### ISSUE TITLE
Small Vec enhancement

### ISSUE THREAD

**Issue by SuperDIMMaX** [AuburnSounds/Dplug#526]
When you call
https://github.com/AuburnSounds/Dplug/blob/e30f3d133123136b7d36bcc94cada178d703ddc0/core/dplug/core/vec.d#L384
you call and
https://github.com/AuburnSounds/Dplug/blob/e30f3d133123136b7d36bcc94cada178d703ddc0/core/dplug/core/vec.d#L324
and it can be reallocate several times.
Maybe `resize` once and directly `_data[i] = x;` ?

**Comment by p0nce** [comment]
Thanks for report! Was a nice idea. `Vec` isn't great.
