### ISSUE TITLE
Smoother behavior

### ISSUE THREAD

**Issue by jpcima** [AuburnSounds/Dplug#529]
Some requests regarding the smoothers.

1. the linear smoother does not reach the final value, it just remains up to one `dy` below.
This behavior is not necessarily to be considered a bug, but is a bit counter-intuitive.

2. it's desired to have a setter for `T _current` for allowing to set the current smooth value.
Other frameworks have this. It's to ensure that a smoother can take the direct value right away on start.
(in particular for synth, for example when keying a new voice)

**Comment by p0nce** [comment]
1. Not sure if easy to fix
2. Absolutely, what I prefer even is to make things auto-initialize, that is the first `nextBuffer` takes the first input as current value.

**Comment by p0nce** [comment]
I don't find the smoothers very good, what would you say of removing them? I feel like anyone can build better ones, and the linear smoother isn't very useful either.

**Comment by jpcima** [comment]
It's your choice, personnally it's a nice thing to have these readily available in the framework.

I notice how `LinearSmoother` can be slightly simplified.
If phase decrements toward zero, the `firstNextAfterInit` can then be eliminated, and `period` will have the possibility to be dynamically changed.
```
        _phase -= _sampleRateInv;
        if (_phase < 0)
            _phase = _period;
```

**Comment by p0nce** [comment]
Smoothers deprecated, one can copy them in own tree to fix them.
