### ISSUE TITLE
"VST" => "VST2"

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#540]
- [x] dplug-build parsing "VST2" instead of "VST"
- [x] version identifier being "VST2", do not use "VST" anymore. Warning that "VST" is a deprecated version identifier
- [x] renaming module-vst.lst to module-vst2.lst
- [x] Update examples
- [x] rename package `dplug:vst` to `dplug:vst2`
- [x] changelog entry

**Comment by 0xEAB** [comment]
- [ ] Update wiki entry

**Comment by p0nce** [comment]
- [ ] "VST2" label in Windows installer

**Comment by p0nce** [comment]
Done as of v9.0.2 + dplug-build at a0298c94182443191eb083818ea61895539fdba5
