### ISSUE TITLE
Additional way to resize without preserving aspect ratio

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#562]
There is no way currently to have a plugin whose valid size are discrete, and without preserving aspect ratio. But I believe this is needed for Convergence?

**Comment by p0nce** [comment]
@abaga129 need this?

The problem with continuous resizing with `SizeConstraints.Type.rectangularBounds` is that continuous resizing require more memory churn so it might be more resource intensive when resizing, and on Linux I'm not sure of the effect.
So I'd advise to have some way to round those size to nearest multiple of something.

**Comment by abaga129** [comment]
> @abaga129 need this?
> 
> The problem with continuous resizing with `SizeConstraints.Type.rectangularBounds` is that continuous resizing require more memory churn so it might be more resource intensive when resizing, and on Linux I'm not sure of the effect.
> So I'd advise to have some way to round those size to nearest multiple of something.

Yes Convergences does have one set of widgets that do resize without preserving aspect ratio. They have a fixed height with a width that can be resized.

**Comment by p0nce** [comment]
For those non-fixed-aspect-ratios plugins: a new `SizeConstraints` type appeared in Dplug v12.0.5
