### ISSUE TITLE
Tracktion + MIDI effect plugin + Windows + VST3 => affect a parameter

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#565]
> In Tracktion Waveform (11.5.18)
MIDI CC data affects a parameter. In Graillon it's the Lead Voice parameter. In Renegate it's the Threshold parameter. It doesn't seem to matter which CC# is being sent. You can test this by adding Graillon or Renegate to a track and sending MIDI CC data to it.

**Comment by p0nce** [comment]
Reproduced, make a note with velocity and a CC and lead voice gets reset to 0

**Comment by p0nce** [comment]
Reproduced with Graillon 2.5 and 2.6 but not 2.4

**Comment by p0nce** [comment]
No crash or such problem in Studio One (Live doesn't appear to send CC).

**Comment by PolyVector** [comment]
I can confirm this bug exists in my wip plugin using Waveform 11.5, and 12 on Linux.  Any CC message (including pitchbend/modulation) will alter the first parameter of a VST3.  In my case this is Global Gain, so it wreaks havoc.

It appears the CC messages are somehow showing up as a param track and being passed along to setParamValue() inside of process() in client.d.

I want to say this is a Waveform bug, but I can't reproduce it with other VST3 plugins (Diva, Dexed, etc).

**Comment by p0nce** [comment]
Why is Tracktion passing CC into setParamValue() though?

**Comment by p0nce** [comment]
It is probably related to a legacy way to receive CC input in VST3.
Perhaps implementing IMidiLean would avoid that.

**Comment by PolyVector** [comment]
> (EDIT: ooh you are right this is always the first parameter. Impossible to add a fake one without an Option though, as this is breaking sessions).
True, but it's a quick fix for unreleased plugins.

> It is probably related to a legacy way to receive CC input in VST3.
Interesting!  You might be on to something with that, it does feel like a legacy/compatibility thing.

**Comment by p0nce** [comment]
> True, but it's a quick fix for unreleased plugins.

Absolutely, and also forward compatible, in the sense that it will still work if we ever implement IMIDILearn (assuming that's the underlying issue for Tracktion).
