### ISSUE TITLE
UI Knob small issue on getting back the values

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#617]
Hello guys !
I have a strange behavior on my current plug in 🙂
it's about the UI...
- I am using ableton live, 
- I open my plug in, the UI appears... 
- 
<img width="565" alt="Capture_decran_2022-01-20_a_10 31 46" src="https://user-images.githubusercontent.com/5418246/150631132-b8bbb5bd-e257-4323-87c0-d54f9ec8acf9.png">

- if I click on the UI Knobs (in the UI window of the plugin)... the values changes, perfect, 
- but, if I use the ableton live window (located at the bottom of the Ableton live window, see screenshot) where all the parameters are visible, and I change in this specific window the values, then the UI is not refreshed, 

I put a screenshot , 
Thanks.

**Comment by p0nce** [comment]
Is your widget custom by any chance?
Usually it can be two things:
- the widget does not register a listener for the parameter: `_param.addListener(this);` and `_param.removeListener(this);`
- it needs to call `setDirtyWhole` in `onParameterChanged` so that the widgets is redrawn

Is it VST2 VST3 or AU ?
I'm looking for such a VST3 + Linux bug actually.

**Comment by rstephane** [comment]
The issue comes on VST2
If I use VST3, it works fine 
I am trying rigth now the AU version,
I keep you inform in a few.

**Comment by rstephane** [comment]
Oki, here are some precisions : important I guess :)
- the issue on my appears on the VERTICAL Knobs, UIFilmStrip (and not on the rotary Knobs ! )

I put a screenshot ...
<img width="228" alt="Capture d’écran 2022-01-25 à 10 47 18" src="https://user-images.githubusercontent.com/5418246/150952821-98922645-9eb8-491b-8805-97fa52accc0e.png">

**Comment by p0nce** [comment]
Hello, i've fixed the bug in v12.3.2 (use `dub upgrade` to get the fix).
It was simply `UIFilmstripSlider` not adding itself as a listener.

**Comment by rstephane** [comment]
aie ! I forgot to upgrade that's true .. gggrrr my fault !

**Comment by p0nce** [comment]
No the fix is from today thanks to your report :)
