### ISSUE TITLE
update the notarization guide for the altool and stapler tool password

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#625]
Hello,
In the wiki, page Notarization guide, we may explain/add that : 

If you put a password in **plugin.json** and then it is included by compiling in your plugin, then your password leak :-( 

If you do so, you will get an error like: 

```
building configuration "VST3"...
../../client/dplug/client/client.d(1006,19): Error: uncaught CTFE exception object.Exception("\x0a*************************** WARNING ***************************\x0a\x0a  This build is using a plain text password in plugin.json\x0a  This will leak through import("plugin.json")\x0a\x0a  Solution:\x0a       Use environment variables, such as:\x0a           \"appSpecificPassword-altool\": \"$APP_SPECIFIC_PASSWORD\"\x0a\x0a***************************************************************\x0a")
```

To avoid that, you have to create an environment variable (exemple on MAC OS : .bash_profile) and do it like that:
[...]
export ALTOOL_SPECIFIC_PASSWORD = "xxx-xxx-yyy-eee"
export STAPLER_SPECIFIC_PASSWORD = "ccc-aaa-yyy-zzz"
[...]
quit your terminal window (or reload your .profile file to setup the two new variables in your environment).

then in the **plugin.json** file, add the following lines :
[...]
"appSpecificPassword-altool": "$ALTOOL_SPECIFIC_PASSWORD",
"appSpecificPassword-stapler": "$STAPLER_SPECIFIC_PASSWORD",
[...]

you can now compile :-)

**Comment by p0nce** [comment]
- [ ] Add to wiki the recommendation to have Xcode 12.2+ for arm64 support
