### ISSUE TITLE
Wren classes are known without the Wren import

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#626]
It doesn't make sense to me, but it seems you can forget to import a class from "widgets", and it still work.  (!!?)

**Comment by PolyVector** [comment]
I've noticed that Wren knows about any class exported in a @ScriptExport section, and you do not need to "import" from your wren script.

Conversely, I have some classes that I explicitly import in wren without needing a @ScriptExport, but that doesn't work, soI'm forced to use a @ScriptExport anyways!  This has led to the following code in my project:
```
@ScriptExport
{
...
	UISeparator ForceScriptToImportSeparators; // For some reason importing directly in the script isn't enough
}
```

**Comment by p0nce** [comment]
Something else annoying with Wren?

**Comment by PolyVector** [comment]
> `@ScriptExport` is indeed always needed (unless you use `context.wrenSupport.registerUIElementClass!UISeparator` to do it for each class manually, this is equivalent).
Ah! That makes sense!  I should have taken more time to understand how this works, thank you.

**Comment by p0nce** [comment]
Well this isn't really disrupting.
