### ISSUE TITLE
console-colors error on dplug-build

### ISSUE THREAD

**Issue by janivaltteri** [AuburnSounds/Dplug#632]
Hello,

On my setup (Arch Linux, DUB 1.27.0, ldc 1.28.1) `dplug-build` currently fails to build the examples with an error:

```
Error: illegal character >, do you mean &gt;?

  <lgreen>=> Bundling plug-in </lgreen>...
  ---------^
```

which I believe is coming from console-colors.

**Comment by p0nce** [comment]
Fixed in master now.
