### ISSUE TITLE
Elements with no zOrder specified recieve Mouse Events back-to-front

### ISSUE THREAD

**Issue by PolyVector** [AuburnSounds/Dplug#652]
Hello,
I've noticed that if I don't call setZOrder() on UIElements, they will receive events like onMouseOver and onMouseClick in the wrong order (back-to-front).  This is causing an issue for me where a "popup" dialog for credits allows clicking through to the knobs below.

This is easily resolved by setting the zOrder to anything above 0.

It appears this is caused by the list being built back-to-front, and the sorting algorithm leaving this untouched if zOrder values match.  I believe building the list front-to-back would solve the issue.

_From element.d_
```
    final void recomputeZOrderedChildren()
    {
        // Get a z-ordered list of childrens
        _zOrderedChildren.clearContents();
        foreach(child; _children[]) // ### The culprit? Children should probably be added in reverse order
            _zOrderedChildren.pushBack(child);

        // This is a stable sort, so the order of children with same z-order still counts.
        grailSort!UIElement(_zOrderedChildren[],
```

Here's a quick demonstration of the problem: [zOrderBug.zip](https://github.com/AuburnSounds/Dplug/files/8672630/zOrderBug.zip)

**Comment by p0nce** [comment]
Thanks for an excellent bug report! I'm please that you use so much Wren already :) 
Did you know we have a new Discord?  https://discord.com/invite/7PdUvUbyJs

And indeed, I think you are right with the bug and the solution too.
TODO
- [ ] compare with HTML
- [ ] Make an Option to use that 

Because this could break existing plugins, the new behaviour will be guarded behind a "futureXXX" Options before becoming default.

(unrelated: zOrder is broken with PBR and Raw layers, as Raw widgets are always displayed above PBR ones, so even if their zOrder disagree they could be in another display order. Never occured yet as bug)

**Comment by p0nce** [comment]
```
<!doctype html>
<html>
<body>
  <div style="color: red; position: absolute; top: 10px; left: 10px; width: 50px; height: 50px; background: yellow">First</div>
  <div style="color: green; position: absolute; top: 20px; left: 20px; width: 50px; height: 50px; background: pink">Second</div>
  <div style="color: blue; position: absolute; top: 30px; left: 30px; width: 50px; height: 50px; background: black">Third</div>
</div>
</body>
</html>
```

leads to

![image](https://user-images.githubusercontent.com/1067485/167936542-d67b0593-a46b-490b-82a4-fa37c39baf8e.png)


so indeed what the rule should be that next in the array of children => first to draw.

**Comment by PolyVector** [comment]
LOL, you just made me realize I left the entire Wren script from my WiP plugin in there even though the test doesn't use it.  Oops!

Yeah, Dplug+Wren has been amazing for quickly iterating, it sure beats my old Krita exporter that spit out layout information.

I'm glad if the report was helpful, and a futureXXX option sounds like a safe bet. :)

**Comment by p0nce** [comment]
Tip: RGBA now have `.blacken(t)` and `whiten(t)`, method that make the color darker or whiter. It is like your `darkenColor` and `lightenColor`. Deleting the Wren file!

**Comment by p0nce** [comment]
Solution: use Dplug v12.6.0+ and add
```json
"versions": ["futureZOrder"],
```

to your `dub.json`.
