### ISSUE TITLE
Documentation imporvement : Linux Section

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#659]
Dear Ponce, 
I installed a linux system and created my first Linux LV2 plug in :) 
Everything was really easy to install, the getting started is really excellent. 
£I noticed however, one point missing for the Linux insxtallation:
- at a point, you need to install also on your linux distribution the X11 libs :-), it's not mentionned and if you try to compile without this lib, you got an error. 

Is it feasible to add in the documentation ? 

_"You might have to install a package to get the X11 development libraries. On Linux, the package is called libX11-dev. To install,
for Redhat, Fedora, etc. : sudo yum install libX11-dev   
 for Ubuntu, etc. : sudo apt-get install libX11-dev" 
(source : https://askubuntu.com/questions/526848/cmake-cant-find-X11)_

Thanks !

**Comment by p0nce** [comment]
Good suggestion, thanks!

**Comment by p0nce** [comment]
Added that in https://github.com/AuburnSounds/Dplug/wiki/Getting-Started
