### ISSUE TITLE
CLAP Client

### ISSUE THREAD

**Issue by BillyDM** [AuburnSounds/Dplug#670]
Does Dplug have any plans to support the new CLAP audio plugin standard?

https://github.com/free-audio/clap

**Comment by p0nce** [comment]
At the moment adding CLAP support doesn’t add much value to Dplug users. This may change if CLAP becomes more ubiquitous than the collection of other formats already available in Dplug, but until then it’s unlikely to be a better use of the Dplug team’s time.

**Comment by p0nce** [comment]
CLAP has soon support in S1 and FLStudio it turns out

**Comment by p0nce** [comment]
- [ ] basic entry point
- [ ] `dplug-build` support

**Comment by p0nce** [comment]
Receiving great help at the CLAP discord

**Comment by p0nce** [comment]
I think it's finished phew
