### ISSUE TITLE
crash (due to UI) when uploading the VST plugin into DAW

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#677]
Dear Dplug community, 

I noticed a UI crash when uploading my VST plug into Ableton live 10. 

I write in the gui.d file : 

// Exciter Drive...
UIFilmstripSlider exciterDriveKnob = mallocNew!UIFilmstripSlider(context(), cast(FloatParameter) _client.param(paramExciterDrive), knobExciterDriveImage, knobDriveFrames);
addChild(exciterDriveKnob);

I compile, and upload the result (plugin.vst) into the DAW, I got a crash. (ableton live is closing).

If now I write in the guid.d file : 
addChild(exciterDriveKnob = mallocNew!UIFilmstripSlider(context(), cast(FloatParameter) _client.param(paramExciterDrive), knobExciterDriveImage, knobDriveFrames));

It doesnot crash :)
I noticed that this happens only for SLIDER object (not for the knobs object).

any idea ? 
Cheers.

**Comment by p0nce** [comment]
Hello,

**Test 1**
Most probably: there is something in your draw method, try to comment out the `onDrawRaw` function in `UIFilmstripSlider ` (warning: watch out when modifying your local Dplug copy).
If it crashes, it may be the image-loading.

**Test 2**
Is this Ableton specific?
Is this format specific?
Only on Windows or only on Mac? This can all help pointing out the bug.

**Comment by p0nce** [comment]
mmmm reading flatslider.d, there is just no support for resizing the input image, which will crash. `UIFilmstripSlider` needs to be more like `UIImageSwitch`.

**Comment by p0nce** [comment]
I can do this in a few days is that ok for you? (say Tuesday)

**Comment by rstephane** [comment]
Hello,
take your time, no hurry / urgency about this. 
:-)

**Comment by p0nce** [comment]
This is fixed in v12.7.10
