### ISSUE TITLE
Wren Memory Leaks

### ISSUE THREAD

**Issue by PolyVector** [AuburnSounds/Dplug#700]
A couple memory leaks regarding Wren:

- [x] wrensupport.d: updateAndReturnIfChanged() leaks a copy of lastSource whenever lastSource==newSource, which happens on repeat calls.
- [ ] wrensupport.d: callPluginMethod()->interpret()->wrenInterpret() appeared to be leaking, but I forgot to take notes on this.  I believe this function was in the Wren library itself and not part of Dplug.

**Comment by p0nce** [comment]
For the second leak, need some Intel Inspector help.

**Comment by p0nce** [comment]
Closed, moved to Wren repo. We do have a number of leaks in Dplug, see #301 for example
