### ISSUE TITLE
Support for Linux aarch64/arm64 builds

### ISSUE THREAD

**Issue by falkTX** [AuburnSounds/Dplug#706]
Hi there!

Just noticed Dplug only supports a few hardcoded architectures.
In the interest of trying to at least get Linux ARM64 (aka aarch64) working, I patched the sources a bit until the operation succeeded.

Very little changes needed:

```diff
--- a/tools/dplug-build/source/arch.d
+++ b/tools/dplug-build/source/arch.d
@@ -51,7 +51,7 @@ string convertArchToDUBFlag(Arch arch) pure
         case arm32:  return "";
 
         // LLVM Triple for Apple Silicon
-        case arm64:  return "--arch=arm64-apple-macos ";
+        case arm64:  return "--arch=aarch64 ";
 
         case universalBinary: assert(false);
         case all: assert(false);
@@ -132,6 +132,8 @@ Arch[] allArchitecturesWeCanBuildForThisOS(OS targetOS)
                 return [ Arch.x86_64]; // we have no support for 32-bit plug-ins on Linux
             else if (buildArch == Arch.arm32)
                 return [ Arch.arm32];
+            else if (buildArch == Arch.arm64)
+                return [ Arch.arm64];
             else
                 throw new Exception("dplug-build on Linux should be built with a x86_64 or arm32 architecture.");
         }
```

I do not know D, so I am afraid this is probably as much as I can help.
Code needs a check for mac vs else on the first diff part, but I don't know how to make those properly in D.

Since this might be of interest to others, I am opening the ticket and including the patch. For posterity and all..

**Comment by p0nce** [comment]
Hello, nice to have you there :)
I'm not sure if `--arch=aarch64` will work on macOS, I think it may well break the macOS build.
Besides, Linux aarch64 is not in the roadmap, so I won't take the patch until it is deemed strategic. It's a big commitment besides being apparently a one-liner, that one is just dplug-build...

**Comment by falkTX** [comment]
Sorry to hear, for what I can see it is just a one-liner on that side that prevents the code from building.
The tool runs and builds plugins fine afterwards.

Since a few opensource plugins are being released made with Dplug and Linux distros are interested on packaging them, you can expect such requests to become more commonplace.
I will keep the patch on my side for arm64 linux builds (for plugins in the KXStudio repositories).

Thanks anyway.

**Comment by p0nce** [comment]
Mmmm didn't know KXStudio support arm64.
I'm not opposed to patches, but that one simply wiped out macOS arm64 support.

**Comment by p0nce** [comment]
Made a replacement patch here => 97a1edf8704c8e8030179e03ddfcd19d39226caf

**Comment by falkTX** [comment]
Yes, that works now.

```
$ CC="aarch64-linux-gnu-gcc" dub --compiler ldc2 --force
Performing "debug" build using ldc2 for aarch64, arm_hardfloat.
arsd-official:characterencodings 10.9.2: building configuration "library"...
arsd-official:dom 10.9.2: building configuration "library"...
commonmark-d 1.0.8: building configuration "library"...
console-colors 1.0.8: building configuration "library"...
intel-intrinsics 1.10.8: building configuration "library"...
dplug:core 12.7.19+commit.6.g97a1edf8: building configuration "library"...
dplug:client 12.7.19+commit.6.g97a1edf8: building configuration "library"...
dplug-build ~master: building configuration "application"...
Linking...
Running dplug-build 

    Congratulations! dplug-build built successfully.
    Type dplug-build --help to know about its usage.
    You'll probably want dplug-build to be in your PATH.

$ file dplug-build
dplug-build: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=edc4b5304b5bae443c2be737f69e886d37fe4c9d, with debug_info, not stripped
```

Thanks!
