### ISSUE TITLE
Reproducible plugin builds on Linux?

### ISSUE THREAD

**Issue by SpotlightKid** [AuburnSounds/Dplug#715]
I am maintaining an Arch user repository package for a Dplug-based GLP plugin, OneTrick SIMIAN here:

https://aur.archlinux.org/packages/ot-simian

We also want to provide binary packages for Arch Linux users via our third-party binary package repository at https://arch.osamc.de/.

We noticed that the produced binaries are not reproducible (as in https://reproducible-builds.org/). On Linux only the ldc2 compiler is supported for compiling Dplug plugins and I could not find out how to make reproducible builds with it.

Do you know whether its is possible to make reproducible builds with Dplug on Linux and, if so, how?

**Comment by p0nce** [comment]
> Do you know whether its is possible to make reproducible builds with Dplug on Linux and, if so, how?

If you want DUB to download the same packages everytime, you need to have a fixed dub.selections.json

**Comment by p0nce** [comment]
I think DUB (used to?) have a way to generate a Makefile too.

**Comment by p0nce** [comment]
Closing, as `dplug-build` itself doesn't do something non-reproducible AFAIK

**Comment by SpotlightKid** [comment]
Thank you for the hint, how to I get dplug-build (or dub) to create a `dub.selections.json` for the plugin. Sorry, I'm not very familiar with D or dub.

But this is not only about pinning dependencies but about byte-level binary reproducibility.

With C/C++ and also dmd you can set the `SOURCE_DATE_EPOCH` environment variable and the compiler should output the same binary bit-for-bit, given the same sources, dependencies, build configuration and value of that env var. I haven't found information on whether ldc2 supports that too. At least it doesn't seem to honor `SOURCE_DATE_EPOCH`. Correct me, if I'm wrong, this may be just due my lack of familiarity with the D ecosystem.

**Comment by p0nce** [comment]
>How to I get dplug-build (or dub) to create a dub.selections.json for the plugin? 

The first `dub` invocation will create such a file if it doesn't exist.
`dub upgrade` updates that file, according to a new dependency resolution (using the latest git tag, usually).
People that want to "pin" dependencies commit this file as part of their build tree, else you opt for Semver updates.
The rest of the dub tool download specified git tag in `dub.selections.json`, on the DUB registry website.

`dplug-build` just call specific `dub` commands.


> `SOURCE_DATE_EPOCH`

Yes, but I don't know if ldc supports that. THe source code of it contain one such envvar test.

**Comment by p0nce** [comment]
Also: do NOT use DMD to make plugins, dmd with -O has slow and unreliable codegen.

**Comment by SpotlightKid** [comment]
No, not yet. Other things had to come fist. I'll be sure to report back if I have new findings.

**Comment by SpotlightKid** [comment]
Just to report: after updating to OneTrick SIMIAN 1.1.0 and building with `dub` directly, [our package build process](https://github.com/osam-cologne/archlinux-proaudio/pull/119) now produces reproducible build.

I'm not sure what caused the change. Maybe the updated Dplug 13.0.5 used by OneTrick SIMIAN 1.1.0?

**Comment by p0nce** [comment]
Possibly the dub.selections.json was commited in SIMIAN source?

**Comment by SpotlightKid** [comment]
Would a missing `dub.selections.json` make two builds, that were executed directly one after another, different? That would be strange.

Another cause could be that we are adding the default Arch `LDFLAGS`, which are defined during the package build with `makepkg` to the `ldflags` in `dub.json`. These flags are currently:

    -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

Maybe this makes the output deterministic.

**Comment by p0nce** [comment]
> Would a missing dub.selections.json make two builds, that were executed directly one after another, different? That would be strange.

dub recomputes the dub.selections.json files and there is a race on the DUB package registry. Probably rare if immediately after. It's probably what you said?
