### ISSUE TITLE
Lanczos3 vs Magic Kernel Sharp 2013

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#729]
100% Plugin UI are beautiful, but when resized it becomes a bit lackluster even with lanczos3.

As described in http://www.johncostella.com/magic/ as "Sharp 2013" kernel.
Is sharper than any lanczos. A bit better with small text, perhaps a bit less "3D". Perhaps a bit too much sharpening going on.

Lanczos3
![test-image pnglanczos3 resized](https://user-images.githubusercontent.com/1067485/199626901-c98af28c-06e0-4f38-ae75-b6d5bbdbfdb6.png)

Sharp 2013
![test-image pngmks2013 resized](https://user-images.githubusercontent.com/1067485/199626906-1b0ce6a8-28a1-456c-9508-0025b27a109d.png)

Lanczos3
![graillon-large pnglanczos3 resized](https://user-images.githubusercontent.com/1067485/199626927-570053dc-8738-4bac-b07a-eb9e3de5c7db.png)

Sharp 2013
![graillon-large pngmks2013 resized](https://user-images.githubusercontent.com/1067485/199626942-fa10271e-d681-4b44-bdeb-7e0abf845176.png)

It's only a few lines to add as a resizing option.
Note: Currently has a memory corruption in the test repo.

**Comment by p0nce** [comment]
Could be less sharpened by blending kernel with non-Sharp Magic Kernel

**Comment by p0nce** [comment]
Many comparisons here, including partially sharp kernels, and MKS + lanczos3 averaged
https://u.pcloud.link/publink/show?code=XZLxMfVZu1n8wFyn3hRdPhrRt5wwbzFyvo4V

**Comment by p0nce** [comment]
Let's decide source by source by mising the 3 channels (Sharp 100%, Sharp 0%, and original lanczos3):
- Simian: best to me is 85% Sharp + none of the Lanczos3 mixed in.

**Comment by p0nce** [comment]
Suggesting 86% Sharp

**Comment by p0nce** [comment]
Now by default in v13.0.4, also wins some speed because the new kernel is 6% faster, and there is no resize anymore if same size was requested.

**Comment by p0nce** [comment]
Whoa it really works.

**Comment by j-p-c** [comment]
Ah sorry, I missed this thread. MKS 2013 indeed contains a slight extra sharpening. MKS 2021 corrects this but is slower.

**Comment by p0nce** [comment]
Hello @j-p-c ,

I've translated `stb_image_resize2.h` into this D package => https://code.dlang.org/my_packages/stb_image_resize2-d
Making one of the fastest and nicest available. Not compared visually since the bits have matched. Thanks again for those excellent kernels.
