### ISSUE TITLE
Error when using presetbank tool

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#765]
Hello,
I am using a MAC 10.15 Catalina. 
I have lcd2-1.26.0. 
I am using dplug ~>12.0

I created VST2 preset program : xxxx.fxp under Ableton Live and also bitwig studio. 
I attached them :-) 

Then I launch presebank "xxx.fxp" "yyyy.fxp" -o "all-presets.fxb"

I got : 

./presetbank "neutral.fxp" "SoftSatu.fxp" -o all-presets.fxb

error: Expected a byte, but found end of input

Usage:
       presetbank <input0> <input1> -o output.fxb

Description:
       Merges presets into one bank.

       Input sources can be:
        - a FXP file whose filename matches the following syntax:
Flags:
        -h, --help  Shows this help
        -o          Output bank. For now, this need to be a .fxb file path.

# end 

Do you have any tips for me to solve the error ? 
cheers.

[presetprogram.zip](https://github.com/AuburnSounds/Dplug/files/11080999/presetprogram.zip)

**Comment by p0nce** [comment]
Thanks for the report! I'll get to it this weekend or when I get some time to work on this.

**Comment by p0nce** [comment]
The issue with neutral.fxp is RIFF header length being stored in Big Endian vs Little Endian as a normal RIFF would mandate.

**Comment by p0nce** [comment]
Should be fixed in v12.8.4 and v13.5.1
Just `dub upgrade`, you don't have to change of major. @rstephane

**Comment by rstephane** [comment]
Thanks !
