### ISSUE TITLE
Undefined symbol "Adler 32" on load on Ubuntu 22.04 + Bitwig 4.4.8 + v12

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#766]
Hello,
When I use bitwig with my VST2 and VST3 plugin (the ones I created myself using Dplug) , the DAW tells me that the plugin has an error : Undefined symobl Adler 32 // Linux Ubuntu

I tried to install zlib that includes adler32... recompile my plugin but the results is the same... 

Bitwig 4.4.8
Dplug : 12.8.x
Linux : Ubuntu Studio 22.04 (kernel 5.15.0.69-lowlaterncy 64 bits)

Tell me if you need more details ? 

Thanks !

**Comment by p0nce** [comment]
Hi, is the plugin built on that system also? Or copied from another linux system?

**Comment by p0nce** [comment]
Seems pretty serious, we shouldn't have any such dynamic dependency.

**Comment by rstephane** [comment]
Hello, yes I compile/build on the OS also...

**Comment by p0nce** [comment]
Additional question: it seems ldc2 calls `cc` now, which is the package you installed? I did a ` apt install clang` , others would not work (only tested "tcc" also, fails at link).

**Comment by p0nce** [comment]
additional question: is it the flatpak Bitwig or the .deb Bitwig?

**Comment by p0nce** [comment]
Linux is so broken. I can't even click in Ardour. I'm in a weird state where bitwig is neither installed, but cannot be removed or fully installed. It is the worse Linux  I ever used.

**Comment by p0nce** [comment]
Weirdly enough the x86 Bitwig .deb in 32-bit x86(i386)

**Comment by p0nce** [comment]
Note to self: Reproducible step to install Bitwig on Ubuntu: launch "Software", NOT "Ubuntu Software" and NOT " Software Updater". Because there is, of course, 3 AppStore app on Ubuntu.

**Comment by p0nce** [comment]
Please post here how you managed to install Bitwig...

**Comment by p0nce** [comment]
**How to install Bitwig here:**
Bitwig 4.4.5 can be installed with .deb, but not 4.4.8 in Ubuntu 22.04
Just change the download URL

**Comment by p0nce** [comment]
And 4.4.5 works, and is a x86_64 .deb ![image](https://user-images.githubusercontent.com/1067485/229537890-87da0303-7683-4379-9d2c-f49ec37abb13.png)

So it is clear Bitwig went from distributing x86_64 software to i386 software, maybe they want to abandon linux.

**Comment by p0nce** [comment]
And the best part is yet to come, if you install Bitwig from a working version (say: 4.4.5) in x86_64 and ` dpkg -i`  your way to 4.4.8, then you can have your plugin run in 4.4.8.
Which means the bug only exist when Bitwig is hosting plugins bridged. Still not reproduced.

**Comment by p0nce** [comment]
There is an adler symbols inside the .so but they are not imported, so can't prevent a load.
So perhaps an error in dub.json

**Comment by p0nce** [comment]
Last time I checked Ubuntu **Studio** did work so this time it seems squarely either in Bitwig camp, or ubuntu **Studio** camp.

**Comment by rstephane** [comment]
Oki thanks, I am going to test all that
