### ISSUE TITLE
FLStudio + Windows + VST3 => doesn't show up

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#779]
Developer reports lack of working for this combination.

**Comment by LunaTheFoxgirl** [comment]
I've tracked the problem down and it turns out to be a fluke, FL Studio scans for specific types of plugins based on folder name. To make FL find a VST3 plugin the folder the VST3 is in needs to be called `VST3`, that was the problem.

**Comment by p0nce** [comment]
Mmm ok, I'm assuming c:\Program Files\Common Files\VST3 worked then
