### ISSUE TITLE
Inner Pitch + macOS Mojave + (Nuendo | Wavelab) => no show

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#800]
> Inner Pitch 1.0.0 runs fine on my Ventura Mac, but not on the old MacPro with Mojave. It doesn’t show up in Nuendo or Wavelab, no VST2, no VST3. Panagament V2 runs fine though. VST2 gets blacklisted by Nuendo 12 as 32 bit plug in. 

User probably has a former Panagement v2.6 that runs ok in Mojave 10.14, not sure why Panagement 2.7 wouldn't have the issue.
We never tried Nuendo 12, possiby reproducible in Cubase too?

**Comment by nkfor** [comment]
I just checked: the Panagement V2 is a 2.4.0 version - will try Panagement 2.7 soon and report back.

**Comment by nkfor** [comment]
Cannot see a Panagement 2.7 version in my itch.io account - only 2.5.1

**Comment by p0nce** [comment]
Whoops indeed that is the last one, there is no 2.7

**Comment by nkfor** [comment]
![InnerPitch_error_AU_TW](https://github.com/AuburnSounds/Dplug/assets/136004082/12aa0957-97ee-4c6f-b2a7-86cb87474adc)
TwistedWave cannot laod the AU version and VST versions are also not visible. Therefore it deosn't seem to be a Steinberg problem.

**Comment by p0nce** [comment]
Something you could try (if you really want to do our job!, since it's quite involved) in the Terminal is to go into the Audio Unit unit directory and try to delete the .rsrc file.
This will be found in: 
`$ cd /Library/Audio/Plug-Ins/Components/Auburn Sounds Inner Pitch.component/Contents/Resources`
`$ ls` or `$ open .`

There should be a .rsrc file there.


`$ del <file.rsrc>`
Deleting the rsrc should force hosts to check the .plist manifest instead, changing the way the AU is loaded.
Something along those lines anyway.

**Comment by nkfor** [comment]
I deleted the .rsrc file without making any difference. No AU or VST version shows up in Acon Acouistica either. Pro Tools 2023.3 also has no .AAX version of Inner Pitch plug in showing up. 
There must be a general problem concerning all Inner Pitch plug in version in Mojave. 
It works, as mentioned, on another Mac with Ventura and on a Win 10 Pro workstation without problems. 
You state compatibility from macOS 10.12 upwards, but there is no go here in 10.14.

**Comment by p0nce** [comment]
OK this seems to be also in #801 so there is some additional problem indeed vs older versions.

**Comment by nkfor** [comment]
I just updated Panagement to the latest 2.5.1 version and it shows up and works fine in all Mojave apps! 
The problem ssems to be Inner Pitch specific. 
Please don't let months pass for fixing this - I really would like to use Inner Pitch on this MacPro.

**Comment by p0nce** [comment]
Hello, we'll do what we can, we have a no-promise policy. Hope yo uunderstand.

**Comment by p0nce** [comment]
Reproduce. The shared library doesn't load, in any DAW, for example the VST doesn't load with dlopen (process).
Dupe of #801.
