### ISSUE TITLE
Wiki: Better env var GUI hint in Dplug VST2 Guide

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#833]
Currently the *Dplug VST2 Guide* links lmgtf in the hint that explains that there’s a fancy GUI for editing environment variables on Windows. It seems that their TLS cert is expired; this leaves the link in the Wiki broken.

Suggested update:

> There's also a fancy GUI for that.
> Check out the “Advanced” tab in `sysdm.cpl` (“System Properties”), there’s a “Environment Variables…” button that opens the graphical editor.

**Comment by 0xEAB** [comment]
Regarding the “Good 1st issue” label,
I’d have fixed this myself. But I don’t have write permissions for the wiki (or can’t find the edit button).

**Comment by p0nce** [comment]
Whoops. Fixed. The wiki editing has been disabled because of bot-spam.

**Comment by 0xEAB** [comment]
No worries :)
Just wanted to point out why I opened this issue.
