### ISSUE TITLE
VST3 bindings auto-generation

### ISSUE THREAD

**Issue by Ogi-kun** [AuburnSounds/Dplug#855]
Because of licensing issues, Dplug forces the users to GPL their VST3 plugins, or writing their own VST3 bindings. I’ve look up how similar  projects handle this. 
[CPAL](https://github.com/RustAudio/cpal) is a Rust library that provides ASIO support. ASIO SDK has a proprietary license that’s virtually identical to the proprietary VST3 license (but unlike VST3, ASIO is not dual-licensed). What they do is they don’t provide Rust translations of the SDK directly. Instead, they provide a tool to generate these translations from the original SDK. This way, they are able to license their code under Apache license without violating proprietary ASIO license. Something like this could be done for Dplug.

**Comment by p0nce** [comment]
> Dplug forces the users to GPL their VST3 plugins

I don't think it's true anymore.
dplug:vst3 is dual-licensed for this reason, please read:

```
// Dual-licence:
// The "Auburn Sounds (Guillaume Piolat) extension to the Steinberg VST 3 Plug-in
// SDK", hereby referred to as DPLUG:VST3, is a language translation of the VST3 
// SDK suitable for usage in Dplug. Any Licensee of a currently valid Steinberg 
// VST 3 Plug-In SDK Licensing Agreement (version 2.2.4 or ulterior, hereby referred
// to as the AGREEMENT), is granted by Auburn Sounds (Guillaume Piolat) a non-exclusive, 
// worldwide, nontransferable license during the term the AGREEMENT to use parts
// of DPLUG:VST3 not covered by the AGREEMENT, as if they were originally 
// inside the Licensed Software Developer Kit mentionned in the AGREEMENT. 
// Under this licence all conditions that apply to the Licensed Software Developer 
// Kit also apply to DPLUG:VST3.
```

We have good relationship with Steinberg and encourage anyone using Dplug to register their plug-in, so there is no licensing issue to solve. I'm pretty sure they see Dplug as insignificant and would reach out should there be a problem.

We reached out years ago to do what you suggest for VST2, and did it with CTFE. Steinberg was for it. It took quite some time for little benefit other than accompany the end of VST2.
