### ISSUE TITLE
[solved] ld: warning: object file (/Users/ .... /dlang/ldc-1.39.0/lib/libphobos2-ldc.a(zutil.c.o)) was built for newer macOS version (10.12) than being linked (10.10)

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#862]
Hello,
While compiling on my mac 10.16 and 14.4 ... I got tjhis warning : 
_"ld: warning: object file (/Users/sribas/dlang/ldc-1.39.0/lib/libphobos2-ldc.a(zutil.c.o)) was built for newer macOS version (10.12) than being linked (10.10)"_

In order to solve it : open  dplug/tools/dbuild-plugin/source/main.d:
search for 
```
version(OSX)
    {
        environment["MACOSX_DEPLOYMENT_TARGET"] = "10.10";
    }
```

and change it for 
```
version(OSX)
    {
        environment["MACOSX_DEPLOYMENT_TARGET"] = "10.12";
    }

```
:-)

**Comment by p0nce** [comment]
Thanks!!!

**Comment by p0nce** [comment]
Fixed in ~master
