### ISSUE TITLE
Windows 10 / Plugin.json / Missing some information in the "examples/distort" plugin

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#866]
Hello,
On windows 10, I have upgraded my Dplug to V14, the latest. I also upgraded LDC2 to 1.39.
I clone the dplug repo to get the latest exemples plugins :-)

Since then, I compiled the "distort" plugin and "dplug-build" sends a message saying that are missing in "plugin.json" : 
"LicencePath"
"IconPath-windows"
"iconPath-osx"

I remember that before my upgrade, I did not need those lines... 

Am i wrong ? 

Anyhow, it's not a big deal as you can add by yourself the lines, but then it could be cool to add them on the github repo also ? 

Regards

**Comment by p0nce** [comment]
The message are very old and those variables are very very optional for a while.

Do you prefer not to see those messages maybe?

**Comment by p0nce** [comment]
- [ ] Produce small licences and showcase macros
- [ ] Hide icon messages, not sure if anyone use them

**Comment by p0nce** [comment]
No more messages!
