### ISSUE TITLE
DPLUG 14.7 // Error: Configuration name given by --config must start with "VST", "VST3", "AU", "AAX", "LV2", or "FLP"

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#871]
Hello,
I can successfully compile with dplug-build -c CLAP , cool ! 
but at the end of the compilation I have the follwing message: 

Error: Configuration name given by --config must start with "VST", "VST3", "AU", "AAX", "LV2", or "FLP"

but as I said, I have the CLAP plugin compiled in builds folder. so no really problem... 

regards.

**Comment by p0nce** [comment]
Hello, this is because `dplug-build` changed to support CLAP.
 - [ ] Change the error message so that `dplug-build` suggest to rebuild

**Comment by p0nce** [comment]
dplug-build master really is buggy
