### ISSUE TITLE
CLAP + FL Studio 24 + macOS ??

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#873]
@rstephane reports lack of detection.

- [ ] What does `nm` says about exported symbols?

**Comment by rstephane** [comment]
MAC OS 13.7 Ventura

**Comment by rstephane** [comment]
hum, I am using LDC1.39 and not 1.36 ... I am going to change it and recompile to see :)
no ?

**Comment by p0nce** [comment]
I don't think it will change much

**Comment by p0nce** [comment]
@rstephane I got CLAP to work in REAPER, it should work for you if you update your plug-build to latest ~master

**Comment by p0nce** [comment]
Test in FL Studio 2024 and works

**Comment by rstephane** [comment]
works fine as well now in reaper & FL ! thanks , what a reactivity !
