### ISSUE TITLE
error while compiling on Linux and get a CLAP version

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#876]
Hello,
On ubuntu 20.04 , I compiled my plugin : 

$ dub build --build=release-nobounds --arch=x86_64 --compiler=ldc2 --combined --config=CLAP
Performing "release-nobounds" build using ldc2 for x86_64.
tarabiafree ~master: building configuration "CLAP"...
../../../.dub/packages/dplug-14.7.1/dplug/clap/dplug/clap/client.d(1196,9): Warning: statement is not reachable
../../../.dub/packages/dplug-14.7.1/dplug/clap/dplug/clap/client.d(1217,9): Warning: statement is not reachable
Error: warnings are treated as errors
       Use -wi if you wish to treat warnings only as informational. 
ldc2 failed with exit code 1.
-- end

Note that under MACOS and Windows, CLAP compilation works fine. 
I did upgrade my dplug version (git pull), etc. :-)

Regards

**Comment by p0nce** [comment]
Hello, if you `dub upgrade` it should be fixed in Dplug v14.7.2
