### ISSUE TITLE
compilation error on linux / CLAP format

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#879]
I am using ubuntu 20.04, LDC version is correct, I have the last DPLUG version also 14.7.2 , dub upgrade done.

when I compile on linux:
$ dub build --build=debug --arch=x86_64 --compiler=ldc2 --config=CLAP
Performing "debug" build using ldc2 for x86_64.
colors 0.0.3: target for configuration "library" is up to date.
intel-intrinsics 1.11.22: target for configuration "library" is up to date.
dplug:core 14.7.2: target for configuration "library" is up to date.
gamut 3.1.1: target for configuration "audio-plugin" is up to date.
canvasity 1.0.1: target for configuration "library" is up to date.
dplug:client 14.7.2: target for configuration "library" is up to date.
dplug:macos 14.7.2: target for configuration "library" is up to date.
dplug:au 14.7.2: target for configuration "library" is up to date.
dplug:clap 14.7.2: building configuration "library"...
../../../.dub/packages/dplug-14.7.2/dplug/clap/dplug/clap/client.d(1227,9): Warning: statement is not reachable
Error: warnings are treated as errors
       Use -wi if you wish to treat warnings only as informational.
ldc2 failed with exit code 1.
error: Command 'dub build --build=debug --arch=x86_64 --compiler=ldc2 --config=CLAP' returned 2

-- END

Notes:
- it works fine for LV2 and VST3
- if I compile under MAC OS / Windows - > CLAP compilation works fine ! 
- I played a lot in copying module-CLAP.lst and .ver other the folders !

**Comment by p0nce** [comment]
Bad fix, I've fixed it should be up in a few minutes.
I think Ubuntu 20.04 may come with older LDC (if using apt-get), so 1.28 or later recommended.

**Comment by p0nce** [comment]
Fixed in v14.7.3

**Comment by p0nce** [comment]
Thanks! Keep the reports coming :)
