### ISSUE TITLE
New website : add a SEARCH field in the section "tutorials" ?

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#884]
Hello,
nice website ;-)
I have a christmas request (you can't refuse, it's christmas time .. almost ;-) ) 

Is it possible to add a Search field in the header of the tutorial section. 
In my ideal, the "Search" field should be visible at first sight (a bit like the google search - big field). 

Thanks ! 
(and of course, no hurry and if it is not possible, I can live without, no prob.)

**Comment by p0nce** [comment]
Would be cool, but I'm fed up with that task right now

**Comment by p0nce** [comment]
Wrong repo => https://github.com/AuburnSounds/Dplug-website2
