### ISSUE TITLE
Template example: missing the file src/module-lv2.lst & src/module-lv2.ver

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#892]
Hello,
I noticed that in the example template provided in Dplug, 2 files seems missing: 
 src/module-lv2.lst & src/module-lv2.ver

When ever you have time can you add them, I can also do a PR if you prefer ?
Don't hesitate.
Regards

**Comment by p0nce** [comment]
Hello,

Fixed in ~master
