### ISSUE TITLE
Using VST chunks for all(?) plugins

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#96]
EDIT:

- [x] Introduce the option futureVST2Chunks
- [x] Use state chunks for both bank chunks and preset banks
- [x] Is Studio One save/load actually supported before chunks are enabled? => no, it's worse => it needs mutability of the preset bank like before, that's why reease plugins don't have the problem.
- [x] Verify: 1/ save 2/load 3/ preset browsing in these hosts: 

* REAPER => OK but need to avoid modifying the bank in memory to keep factory defaults => OK
* Orion => OK
* Cubase => OK but on load preset N+1 is taken
* Bitwig => OK
* Studio One => massive PITA, parameter don't get fucking recalled but original preset is recalled instead...
     Studio One calls setProgram after setting the "bank" chunk
     => log setProgram and getProgram calls => mutates the preset bank again
     Workaround? => do like before
* FLStudio => OK
* Live => OK

Need a fuckton of testing since a wrong implementaton will harm saves.

-------------------------------

Older:

For now I don't think this is necessary but here is how one could do it.

For VST:
- change flags of AEffect
- uncomment `version(useChunks)`

The preset bank will still be modified by state changes, this could be changed later to be constant.
Using chunks is unrelated to this.
It is also unrelated to internal preset management which doesn't necessarily need chunks.
It is also unrelated to parameter versionning which can be handled by a "version" parameter.
##

**Comment by p0nce** [comment]
Question with current situation, does it work whan modifying preset N and save/reloading?

**Comment by p0nce** [comment]
Preset saves using AU save the whole bank though.

**Comment by p0nce** [comment]
Bank chunks were broken and had to be repaired for AU to work.

**Comment by p0nce** [comment]
AU doesn't use bank chunks anymore, it is similar to VST now.

**Comment by p0nce** [comment]
Will be useful if we ever want state without parameters (and we will in the future).

**Comment by p0nce** [comment]
Not having chunks prevents to make some kinds of plugins where state doesn't fit in parameters.

**Comment by p0nce** [comment]
Blocking #191

**Comment by p0nce** [comment]
I don't think there is any way to keep previouly plugins compatible with Chunks. The new system will need to:

- provide arbitrary serialization and deserialization (have to look at IPlug does...)
- automatically save/restore the plugin `Parameter`
- also it won't be possible for preset to just be a list of parameters anymore

**Comment by p0nce** [comment]
I was advised to get out of VST non-chunk as soon as possible. However this breaks save compatibility so for soem period of time it will be necessary to have it optional.

**Comment by 0xEAB** [comment]
I'd suggest to make this a *compile-time decision*. So one could use future versions of Dplug without being forced to break compatibility. Chunks as opt-out is the way to go, imho.

Default option would be using them then of course. Although those who want to continue without them could specify a special version in their `dub.json` in order to do so.

(What I haven't taken into account is the extra work to maintain both variants working - because I don't know how much more complicated this would be.)

**Comment by p0nce** [comment]
> I'd suggest to make this a compile-time decision. So one could use future versions of Dplug without being forced to break compatibility. Chunks as opt-out is the way to go, imho.

Yes indeed, to support existing products there is no other way.

> (What I haven't taken into account is the extra work to maintain both variants working - because I don't know how much more complicated this would be.)
I don't think it's that much work, but it's kind of risky.

**Comment by p0nce** [comment]
**Some use case**: one nice way to implement randomness in a way that is reapeatable is to store a "seed" in the saved chunk, one by plugin instantiation.
Users complain with random LFO being different each time, not repeatable.

**Comment by p0nce** [comment]
To be implemented, guarded with an option so that save compatibility is preserved.

**Comment by p0nce** [comment]
Just enabling VST2 chunks don't work as is, we need **diagrams** to really understand the _presetBank state in Dplug, as it evolved from VST2 requirements that I remember were byzantine (like renaming presets, saving banks also save unselected presets, etc).

**Comment by p0nce** [comment]
https://github.com/AuburnSounds/Dplug/wiki/Roles-of-the-PresetBank

**Comment by p0nce** [comment]
Epidermic reaction:
- save/restore in case of VST2 chunks should be with state chunks only. "bank" will return a single state.
- "preset" and "bank" preset should probably go since nothing uses them.
- letting a VST2 plugin (or AU plugin) mutate the factory presets is maybe not needed. Not sure how VST2 hosts will react if you can't name a preset.
- it would be nice to have a unified way to pass state around (parameters, optional name, optional data...) state chunks are probably a good start

**Comment by p0nce** [comment]
5 YEARS LATER, THIS IS DONE.

See futureVST2Chunks in https://github.com/AuburnSounds/Dplug/wiki/Options for how to opt-in.
This will become an opt-out options someday.
It will take a lot of time, since it breaks user sessions.
